// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: incrideats/incrideats.proto

package incrideatspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ingredient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CategoryId    int64                  `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ingredient) Reset() {
	*x = Ingredient{}
	mi := &file_incrideats_incrideats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ingredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ingredient) ProtoMessage() {}

func (x *Ingredient) ProtoReflect() protoreflect.Message {
	mi := &file_incrideats_incrideats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ingredient.ProtoReflect.Descriptor instead.
func (*Ingredient) Descriptor() ([]byte, []int) {
	return file_incrideats_incrideats_proto_rawDescGZIP(), []int{0}
}

func (x *Ingredient) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Ingredient) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Ingredient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ingredient) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Ingredient) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Ingredient) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateIngredientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      float64                `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CategoryId    int64                  `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIngredientRequest) Reset() {
	*x = CreateIngredientRequest{}
	mi := &file_incrideats_incrideats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIngredientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIngredientRequest) ProtoMessage() {}

func (x *CreateIngredientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_incrideats_incrideats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIngredientRequest.ProtoReflect.Descriptor instead.
func (*CreateIngredientRequest) Descriptor() ([]byte, []int) {
	return file_incrideats_incrideats_proto_rawDescGZIP(), []int{1}
}

func (x *CreateIngredientRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateIngredientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateIngredientRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateIngredientRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type GetIngredientByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIngredientByIDRequest) Reset() {
	*x = GetIngredientByIDRequest{}
	mi := &file_incrideats_incrideats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIngredientByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIngredientByIDRequest) ProtoMessage() {}

func (x *GetIngredientByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_incrideats_incrideats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIngredientByIDRequest.ProtoReflect.Descriptor instead.
func (*GetIngredientByIDRequest) Descriptor() ([]byte, []int) {
	return file_incrideats_incrideats_proto_rawDescGZIP(), []int{2}
}

func (x *GetIngredientByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetIngredientByIDRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetAllIngredientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllIngredientsRequest) Reset() {
	*x = GetAllIngredientsRequest{}
	mi := &file_incrideats_incrideats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllIngredientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllIngredientsRequest) ProtoMessage() {}

func (x *GetAllIngredientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_incrideats_incrideats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllIngredientsRequest.ProtoReflect.Descriptor instead.
func (*GetAllIngredientsRequest) Descriptor() ([]byte, []int) {
	return file_incrideats_incrideats_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllIngredientsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdateIngredientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CategoryId    int64                  `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIngredientRequest) Reset() {
	*x = UpdateIngredientRequest{}
	mi := &file_incrideats_incrideats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIngredientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIngredientRequest) ProtoMessage() {}

func (x *UpdateIngredientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_incrideats_incrideats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIngredientRequest.ProtoReflect.Descriptor instead.
func (*UpdateIngredientRequest) Descriptor() ([]byte, []int) {
	return file_incrideats_incrideats_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateIngredientRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateIngredientRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateIngredientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateIngredientRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateIngredientRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type DeleteIngredientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIngredientRequest) Reset() {
	*x = DeleteIngredientRequest{}
	mi := &file_incrideats_incrideats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIngredientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIngredientRequest) ProtoMessage() {}

func (x *DeleteIngredientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_incrideats_incrideats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIngredientRequest.ProtoReflect.Descriptor instead.
func (*DeleteIngredientRequest) Descriptor() ([]byte, []int) {
	return file_incrideats_incrideats_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteIngredientRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteIngredientRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type IngredientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ingredient    *Ingredient            `protobuf:"bytes,1,opt,name=ingredient,proto3" json:"ingredient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngredientResponse) Reset() {
	*x = IngredientResponse{}
	mi := &file_incrideats_incrideats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngredientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngredientResponse) ProtoMessage() {}

func (x *IngredientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_incrideats_incrideats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngredientResponse.ProtoReflect.Descriptor instead.
func (*IngredientResponse) Descriptor() ([]byte, []int) {
	return file_incrideats_incrideats_proto_rawDescGZIP(), []int{6}
}

func (x *IngredientResponse) GetIngredient() *Ingredient {
	if x != nil {
		return x.Ingredient
	}
	return nil
}

type IngredientListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ingredients   []*Ingredient          `protobuf:"bytes,1,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngredientListResponse) Reset() {
	*x = IngredientListResponse{}
	mi := &file_incrideats_incrideats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngredientListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngredientListResponse) ProtoMessage() {}

func (x *IngredientListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_incrideats_incrideats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngredientListResponse.ProtoReflect.Descriptor instead.
func (*IngredientListResponse) Descriptor() ([]byte, []int) {
	return file_incrideats_incrideats_proto_rawDescGZIP(), []int{7}
}

func (x *IngredientListResponse) GetIngredients() []*Ingredient {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_incrideats_incrideats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_incrideats_incrideats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_incrideats_incrideats_proto_rawDescGZIP(), []int{8}
}

var File_incrideats_incrideats_proto protoreflect.FileDescriptor

const file_incrideats_incrideats_proto_rawDesc = "" +
	"\n" +
	"\x1bincrideats/incrideats.proto\x12\n" +
	"ingredient\"\xa5\x01\n" +
	"\n" +
	"Ingredient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\x03R\n" +
	"categoryId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\x83\x01\n" +
	"\x17CreateIngredientRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x01R\bquantity\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\x03R\n" +
	"categoryId\"C\n" +
	"\x18GetIngredientByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"3\n" +
	"\x18GetAllIngredientsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x93\x01\n" +
	"\x17UpdateIngredientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\x03R\n" +
	"categoryId\"B\n" +
	"\x17DeleteIngredientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"L\n" +
	"\x12IngredientResponse\x126\n" +
	"\n" +
	"ingredient\x18\x01 \x01(\v2\x16.ingredient.IngredientR\n" +
	"ingredient\"R\n" +
	"\x16IngredientListResponse\x128\n" +
	"\vingredients\x18\x01 \x03(\v2\x16.ingredient.IngredientR\vingredients\"\a\n" +
	"\x05Empty2\x98\x03\n" +
	"\x11IngredientService\x12M\n" +
	"\x06Create\x12#.ingredient.CreateIngredientRequest\x1a\x1e.ingredient.IngredientResponse\x12O\n" +
	"\aGetByID\x12$.ingredient.GetIngredientByIDRequest\x1a\x1e.ingredient.IngredientResponse\x12R\n" +
	"\x06GetAll\x12$.ingredient.GetAllIngredientsRequest\x1a\".ingredient.IngredientListResponse\x12M\n" +
	"\x06Update\x12#.ingredient.UpdateIngredientRequest\x1a\x1e.ingredient.IngredientResponse\x12@\n" +
	"\x06Delete\x12#.ingredient.DeleteIngredientRequest\x1a\x11.ingredient.EmptyBCZAgithub.com/khbdev/what-food-proto/proto/incrideatspb;incrideatspbb\x06proto3"

var (
	file_incrideats_incrideats_proto_rawDescOnce sync.Once
	file_incrideats_incrideats_proto_rawDescData []byte
)

func file_incrideats_incrideats_proto_rawDescGZIP() []byte {
	file_incrideats_incrideats_proto_rawDescOnce.Do(func() {
		file_incrideats_incrideats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_incrideats_incrideats_proto_rawDesc), len(file_incrideats_incrideats_proto_rawDesc)))
	})
	return file_incrideats_incrideats_proto_rawDescData
}

var file_incrideats_incrideats_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_incrideats_incrideats_proto_goTypes = []any{
	(*Ingredient)(nil),               // 0: ingredient.Ingredient
	(*CreateIngredientRequest)(nil),  // 1: ingredient.CreateIngredientRequest
	(*GetIngredientByIDRequest)(nil), // 2: ingredient.GetIngredientByIDRequest
	(*GetAllIngredientsRequest)(nil), // 3: ingredient.GetAllIngredientsRequest
	(*UpdateIngredientRequest)(nil),  // 4: ingredient.UpdateIngredientRequest
	(*DeleteIngredientRequest)(nil),  // 5: ingredient.DeleteIngredientRequest
	(*IngredientResponse)(nil),       // 6: ingredient.IngredientResponse
	(*IngredientListResponse)(nil),   // 7: ingredient.IngredientListResponse
	(*Empty)(nil),                    // 8: ingredient.Empty
}
var file_incrideats_incrideats_proto_depIdxs = []int32{
	0, // 0: ingredient.IngredientResponse.ingredient:type_name -> ingredient.Ingredient
	0, // 1: ingredient.IngredientListResponse.ingredients:type_name -> ingredient.Ingredient
	1, // 2: ingredient.IngredientService.Create:input_type -> ingredient.CreateIngredientRequest
	2, // 3: ingredient.IngredientService.GetByID:input_type -> ingredient.GetIngredientByIDRequest
	3, // 4: ingredient.IngredientService.GetAll:input_type -> ingredient.GetAllIngredientsRequest
	4, // 5: ingredient.IngredientService.Update:input_type -> ingredient.UpdateIngredientRequest
	5, // 6: ingredient.IngredientService.Delete:input_type -> ingredient.DeleteIngredientRequest
	6, // 7: ingredient.IngredientService.Create:output_type -> ingredient.IngredientResponse
	6, // 8: ingredient.IngredientService.GetByID:output_type -> ingredient.IngredientResponse
	7, // 9: ingredient.IngredientService.GetAll:output_type -> ingredient.IngredientListResponse
	6, // 10: ingredient.IngredientService.Update:output_type -> ingredient.IngredientResponse
	8, // 11: ingredient.IngredientService.Delete:output_type -> ingredient.Empty
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_incrideats_incrideats_proto_init() }
func file_incrideats_incrideats_proto_init() {
	if File_incrideats_incrideats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_incrideats_incrideats_proto_rawDesc), len(file_incrideats_incrideats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_incrideats_incrideats_proto_goTypes,
		DependencyIndexes: file_incrideats_incrideats_proto_depIdxs,
		MessageInfos:      file_incrideats_incrideats_proto_msgTypes,
	}.Build()
	File_incrideats_incrideats_proto = out.File
	file_incrideats_incrideats_proto_goTypes = nil
	file_incrideats_incrideats_proto_depIdxs = nil
}
