// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: dashboard/dashboard.proto

package dashboardpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_dashboard_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{0}
}

type DashboardStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalUsers    int64                  `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	ActiveUsers   int64                  `protobuf:"varint,2,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	CityStats     []*CityStat            `protobuf:"bytes,3,rep,name=city_stats,json=cityStats,proto3" json:"city_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardStatsResponse) Reset() {
	*x = DashboardStatsResponse{}
	mi := &file_dashboard_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardStatsResponse) ProtoMessage() {}

func (x *DashboardStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardStatsResponse.ProtoReflect.Descriptor instead.
func (*DashboardStatsResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *DashboardStatsResponse) GetTotalUsers() int64 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *DashboardStatsResponse) GetActiveUsers() int64 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

func (x *DashboardStatsResponse) GetCityStats() []*CityStat {
	if x != nil {
		return x.CityStats
	}
	return nil
}

type CityStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CityStat) Reset() {
	*x = CityStat{}
	mi := &file_dashboard_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CityStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityStat) ProtoMessage() {}

func (x *CityStat) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityStat.ProtoReflect.Descriptor instead.
func (*CityStat) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *CityStat) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CityStat) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_dashboard_dashboard_proto protoreflect.FileDescriptor

const file_dashboard_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x19dashboard/dashboard.proto\x12\tdashboard\"\a\n" +
	"\x05Empty\"\x90\x01\n" +
	"\x16DashboardStatsResponse\x12\x1f\n" +
	"\vtotal_users\x18\x01 \x01(\x03R\n" +
	"totalUsers\x12!\n" +
	"\factive_users\x18\x02 \x01(\x03R\vactiveUsers\x122\n" +
	"\n" +
	"city_stats\x18\x03 \x03(\v2\x13.dashboard.CityStatR\tcityStats\"4\n" +
	"\bCityStat\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count2`\n" +
	"\x14UserDashboardService\x12H\n" +
	"\x11GetDashboardStats\x12\x10.dashboard.Empty\x1a!.dashboard.DashboardStatsResponseB?Z=github.com/khbdev/what-food-proto/proto/dashboard;dashboardpbb\x06proto3"

var (
	file_dashboard_dashboard_proto_rawDescOnce sync.Once
	file_dashboard_dashboard_proto_rawDescData []byte
)

func file_dashboard_dashboard_proto_rawDescGZIP() []byte {
	file_dashboard_dashboard_proto_rawDescOnce.Do(func() {
		file_dashboard_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dashboard_dashboard_proto_rawDesc), len(file_dashboard_dashboard_proto_rawDesc)))
	})
	return file_dashboard_dashboard_proto_rawDescData
}

var file_dashboard_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dashboard_dashboard_proto_goTypes = []any{
	(*Empty)(nil),                  // 0: dashboard.Empty
	(*DashboardStatsResponse)(nil), // 1: dashboard.DashboardStatsResponse
	(*CityStat)(nil),               // 2: dashboard.CityStat
}
var file_dashboard_dashboard_proto_depIdxs = []int32{
	2, // 0: dashboard.DashboardStatsResponse.city_stats:type_name -> dashboard.CityStat
	0, // 1: dashboard.UserDashboardService.GetDashboardStats:input_type -> dashboard.Empty
	1, // 2: dashboard.UserDashboardService.GetDashboardStats:output_type -> dashboard.DashboardStatsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dashboard_dashboard_proto_init() }
func file_dashboard_dashboard_proto_init() {
	if File_dashboard_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dashboard_dashboard_proto_rawDesc), len(file_dashboard_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dashboard_dashboard_proto_goTypes,
		DependencyIndexes: file_dashboard_dashboard_proto_depIdxs,
		MessageInfos:      file_dashboard_dashboard_proto_msgTypes,
	}.Build()
	File_dashboard_dashboard_proto = out.File
	file_dashboard_dashboard_proto_goTypes = nil
	file_dashboard_dashboard_proto_depIdxs = nil
}
