// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: dashboard/dashboard.proto

package dashboardpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserDashboardService_GetDashboardStats_FullMethodName = "/dashboard.UserDashboardService/GetDashboardStats"
)

// UserDashboardServiceClient is the client API for UserDashboardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserDashboardServiceClient interface {
	GetDashboardStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DashboardStatsResponse, error)
}

type userDashboardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserDashboardServiceClient(cc grpc.ClientConnInterface) UserDashboardServiceClient {
	return &userDashboardServiceClient{cc}
}

func (c *userDashboardServiceClient) GetDashboardStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DashboardStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DashboardStatsResponse)
	err := c.cc.Invoke(ctx, UserDashboardService_GetDashboardStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserDashboardServiceServer is the server API for UserDashboardService service.
// All implementations must embed UnimplementedUserDashboardServiceServer
// for forward compatibility.
type UserDashboardServiceServer interface {
	GetDashboardStats(context.Context, *Empty) (*DashboardStatsResponse, error)
	mustEmbedUnimplementedUserDashboardServiceServer()
}

// UnimplementedUserDashboardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserDashboardServiceServer struct{}

func (UnimplementedUserDashboardServiceServer) GetDashboardStats(context.Context, *Empty) (*DashboardStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDashboardStats not implemented")
}
func (UnimplementedUserDashboardServiceServer) mustEmbedUnimplementedUserDashboardServiceServer() {}
func (UnimplementedUserDashboardServiceServer) testEmbeddedByValue()                              {}

// UnsafeUserDashboardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserDashboardServiceServer will
// result in compilation errors.
type UnsafeUserDashboardServiceServer interface {
	mustEmbedUnimplementedUserDashboardServiceServer()
}

func RegisterUserDashboardServiceServer(s grpc.ServiceRegistrar, srv UserDashboardServiceServer) {
	// If the following call panics, it indicates UnimplementedUserDashboardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserDashboardService_ServiceDesc, srv)
}

func _UserDashboardService_GetDashboardStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDashboardServiceServer).GetDashboardStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDashboardService_GetDashboardStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDashboardServiceServer).GetDashboardStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// UserDashboardService_ServiceDesc is the grpc.ServiceDesc for UserDashboardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserDashboardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dashboard.UserDashboardService",
	HandlerType: (*UserDashboardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDashboardStats",
			Handler:    _UserDashboardService_GetDashboardStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dashboard/dashboard.proto",
}
