// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: feedback/feedback.proto

package nutritionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DayNutrition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           string                 `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	Kcal          int32                  `protobuf:"varint,2,opt,name=kcal,proto3" json:"kcal,omitempty"`
	Fat           int32                  `protobuf:"varint,3,opt,name=fat,proto3" json:"fat,omitempty"`
	Carbs         float64                `protobuf:"fixed64,4,opt,name=carbs,proto3" json:"carbs,omitempty"`
	Protein       int32                  `protobuf:"varint,5,opt,name=protein,proto3" json:"protein,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DayNutrition) Reset() {
	*x = DayNutrition{}
	mi := &file_feedback_feedback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DayNutrition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayNutrition) ProtoMessage() {}

func (x *DayNutrition) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_feedback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayNutrition.ProtoReflect.Descriptor instead.
func (*DayNutrition) Descriptor() ([]byte, []int) {
	return file_feedback_feedback_proto_rawDescGZIP(), []int{0}
}

func (x *DayNutrition) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *DayNutrition) GetKcal() int32 {
	if x != nil {
		return x.Kcal
	}
	return 0
}

func (x *DayNutrition) GetFat() int32 {
	if x != nil {
		return x.Fat
	}
	return 0
}

func (x *DayNutrition) GetCarbs() float64 {
	if x != nil {
		return x.Carbs
	}
	return 0
}

func (x *DayNutrition) GetProtein() int32 {
	if x != nil {
		return x.Protein
	}
	return 0
}

type NutritionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          []*DayNutrition        `protobuf:"bytes,1,rep,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NutritionRequest) Reset() {
	*x = NutritionRequest{}
	mi := &file_feedback_feedback_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NutritionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NutritionRequest) ProtoMessage() {}

func (x *NutritionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_feedback_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NutritionRequest.ProtoReflect.Descriptor instead.
func (*NutritionRequest) Descriptor() ([]byte, []int) {
	return file_feedback_feedback_proto_rawDescGZIP(), []int{1}
}

func (x *NutritionRequest) GetDays() []*DayNutrition {
	if x != nil {
		return x.Days
	}
	return nil
}

type NutritionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feedback      string                 `protobuf:"bytes,1,opt,name=feedback,proto3" json:"feedback,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NutritionResponse) Reset() {
	*x = NutritionResponse{}
	mi := &file_feedback_feedback_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NutritionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NutritionResponse) ProtoMessage() {}

func (x *NutritionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_feedback_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NutritionResponse.ProtoReflect.Descriptor instead.
func (*NutritionResponse) Descriptor() ([]byte, []int) {
	return file_feedback_feedback_proto_rawDescGZIP(), []int{2}
}

func (x *NutritionResponse) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *NutritionResponse) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

var File_feedback_feedback_proto protoreflect.FileDescriptor

const file_feedback_feedback_proto_rawDesc = "" +
	"\n" +
	"\x17feedback/feedback.proto\x12\tnutrition\"v\n" +
	"\fDayNutrition\x12\x10\n" +
	"\x03day\x18\x01 \x01(\tR\x03day\x12\x12\n" +
	"\x04kcal\x18\x02 \x01(\x05R\x04kcal\x12\x10\n" +
	"\x03fat\x18\x03 \x01(\x05R\x03fat\x12\x14\n" +
	"\x05carbs\x18\x04 \x01(\x01R\x05carbs\x12\x18\n" +
	"\aprotein\x18\x05 \x01(\x05R\aprotein\"?\n" +
	"\x10NutritionRequest\x12+\n" +
	"\x04days\x18\x01 \x03(\v2\x17.nutrition.DayNutritionR\x04days\"E\n" +
	"\x11NutritionResponse\x12\x1a\n" +
	"\bfeedback\x18\x01 \x01(\tR\bfeedback\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level2\\\n" +
	"\vMailService\x12M\n" +
	"\x10AnalyzeNutrition\x12\x1b.nutrition.NutritionRequest\x1a\x1c.nutrition.NutritionResponseB\x1bZ\x19gen/nutrition;nutritionpbb\x06proto3"

var (
	file_feedback_feedback_proto_rawDescOnce sync.Once
	file_feedback_feedback_proto_rawDescData []byte
)

func file_feedback_feedback_proto_rawDescGZIP() []byte {
	file_feedback_feedback_proto_rawDescOnce.Do(func() {
		file_feedback_feedback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feedback_feedback_proto_rawDesc), len(file_feedback_feedback_proto_rawDesc)))
	})
	return file_feedback_feedback_proto_rawDescData
}

var file_feedback_feedback_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_feedback_feedback_proto_goTypes = []any{
	(*DayNutrition)(nil),      // 0: nutrition.DayNutrition
	(*NutritionRequest)(nil),  // 1: nutrition.NutritionRequest
	(*NutritionResponse)(nil), // 2: nutrition.NutritionResponse
}
var file_feedback_feedback_proto_depIdxs = []int32{
	0, // 0: nutrition.NutritionRequest.days:type_name -> nutrition.DayNutrition
	1, // 1: nutrition.MailService.AnalyzeNutrition:input_type -> nutrition.NutritionRequest
	2, // 2: nutrition.MailService.AnalyzeNutrition:output_type -> nutrition.NutritionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_feedback_feedback_proto_init() }
func file_feedback_feedback_proto_init() {
	if File_feedback_feedback_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feedback_feedback_proto_rawDesc), len(file_feedback_feedback_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feedback_feedback_proto_goTypes,
		DependencyIndexes: file_feedback_feedback_proto_depIdxs,
		MessageInfos:      file_feedback_feedback_proto_msgTypes,
	}.Build()
	File_feedback_feedback_proto = out.File
	file_feedback_feedback_proto_goTypes = nil
	file_feedback_feedback_proto_depIdxs = nil
}
