// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ai/ai.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Meal
type MealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	MealTime      string                 `protobuf:"bytes,4,opt,name=meal_time,json=mealTime,proto3" json:"meal_time,omitempty"`
	Kcal          float32                `protobuf:"fixed32,5,opt,name=kcal,proto3" json:"kcal,omitempty"`
	Protein       float32                `protobuf:"fixed32,6,opt,name=protein,proto3" json:"protein,omitempty"`
	Fat           float32                `protobuf:"fixed32,7,opt,name=fat,proto3" json:"fat,omitempty"`
	Carbs         float32                `protobuf:"fixed32,8,opt,name=carbs,proto3" json:"carbs,omitempty"`
	Portion       int32                  `protobuf:"varint,9,opt,name=portion,proto3" json:"portion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MealRequest) Reset() {
	*x = MealRequest{}
	mi := &file_ai_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealRequest) ProtoMessage() {}

func (x *MealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealRequest.ProtoReflect.Descriptor instead.
func (*MealRequest) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{0}
}

func (x *MealRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MealRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MealRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *MealRequest) GetMealTime() string {
	if x != nil {
		return x.MealTime
	}
	return ""
}

func (x *MealRequest) GetKcal() float32 {
	if x != nil {
		return x.Kcal
	}
	return 0
}

func (x *MealRequest) GetProtein() float32 {
	if x != nil {
		return x.Protein
	}
	return 0
}

func (x *MealRequest) GetFat() float32 {
	if x != nil {
		return x.Fat
	}
	return 0
}

func (x *MealRequest) GetCarbs() float32 {
	if x != nil {
		return x.Carbs
	}
	return 0
}

func (x *MealRequest) GetPortion() int32 {
	if x != nil {
		return x.Portion
	}
	return 0
}

type Ingredient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ingredient) Reset() {
	*x = Ingredient{}
	mi := &file_ai_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ingredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ingredient) ProtoMessage() {}

func (x *Ingredient) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ingredient.ProtoReflect.Descriptor instead.
func (*Ingredient) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{1}
}

func (x *Ingredient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ingredient) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type MealResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Portion            int32                  `protobuf:"varint,1,opt,name=portion,proto3" json:"portion,omitempty"`
	TotalKcal          float32                `protobuf:"fixed32,2,opt,name=total_kcal,json=totalKcal,proto3" json:"total_kcal,omitempty"`
	CookingTimeMinutes int32                  `protobuf:"varint,3,opt,name=cooking_time_minutes,json=cookingTimeMinutes,proto3" json:"cooking_time_minutes,omitempty"`
	Ingredients        []*Ingredient          `protobuf:"bytes,4,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	Steps              []string               `protobuf:"bytes,5,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MealResponse) Reset() {
	*x = MealResponse{}
	mi := &file_ai_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealResponse) ProtoMessage() {}

func (x *MealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealResponse.ProtoReflect.Descriptor instead.
func (*MealResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{2}
}

func (x *MealResponse) GetPortion() int32 {
	if x != nil {
		return x.Portion
	}
	return 0
}

func (x *MealResponse) GetTotalKcal() float32 {
	if x != nil {
		return x.TotalKcal
	}
	return 0
}

func (x *MealResponse) GetCookingTimeMinutes() int32 {
	if x != nil {
		return x.CookingTimeMinutes
	}
	return 0
}

func (x *MealResponse) GetIngredients() []*Ingredient {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

func (x *MealResponse) GetSteps() []string {
	if x != nil {
		return x.Steps
	}
	return nil
}

// Nutrition
type NutritionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	AvgKcal       float32                `protobuf:"fixed32,2,opt,name=avg_kcal,json=avgKcal,proto3" json:"avg_kcal,omitempty"`
	AvgProtein    float32                `protobuf:"fixed32,3,opt,name=avg_protein,json=avgProtein,proto3" json:"avg_protein,omitempty"`
	AvgFat        float32                `protobuf:"fixed32,4,opt,name=avg_fat,json=avgFat,proto3" json:"avg_fat,omitempty"`
	AvgCarbs      float32                `protobuf:"fixed32,5,opt,name=avg_carbs,json=avgCarbs,proto3" json:"avg_carbs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NutritionRequest) Reset() {
	*x = NutritionRequest{}
	mi := &file_ai_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NutritionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NutritionRequest) ProtoMessage() {}

func (x *NutritionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NutritionRequest.ProtoReflect.Descriptor instead.
func (*NutritionRequest) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{3}
}

func (x *NutritionRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *NutritionRequest) GetAvgKcal() float32 {
	if x != nil {
		return x.AvgKcal
	}
	return 0
}

func (x *NutritionRequest) GetAvgProtein() float32 {
	if x != nil {
		return x.AvgProtein
	}
	return 0
}

func (x *NutritionRequest) GetAvgFat() float32 {
	if x != nil {
		return x.AvgFat
	}
	return 0
}

func (x *NutritionRequest) GetAvgCarbs() float32 {
	if x != nil {
		return x.AvgCarbs
	}
	return 0
}

type NutritionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feedback      string                 `protobuf:"bytes,1,opt,name=feedback,proto3" json:"feedback,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NutritionResponse) Reset() {
	*x = NutritionResponse{}
	mi := &file_ai_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NutritionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NutritionResponse) ProtoMessage() {}

func (x *NutritionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NutritionResponse.ProtoReflect.Descriptor instead.
func (*NutritionResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{4}
}

func (x *NutritionResponse) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *NutritionResponse) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

var File_ai_ai_proto protoreflect.FileDescriptor

const file_ai_ai_proto_rawDesc = "" +
	"\n" +
	"\vai/ai.proto\x12\x02ai\"\xea\x01\n" +
	"\vMealRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x1b\n" +
	"\tmeal_time\x18\x04 \x01(\tR\bmealTime\x12\x12\n" +
	"\x04kcal\x18\x05 \x01(\x02R\x04kcal\x12\x18\n" +
	"\aprotein\x18\x06 \x01(\x02R\aprotein\x12\x10\n" +
	"\x03fat\x18\a \x01(\x02R\x03fat\x12\x14\n" +
	"\x05carbs\x18\b \x01(\x02R\x05carbs\x12\x18\n" +
	"\aportion\x18\t \x01(\x05R\aportion\"8\n" +
	"\n" +
	"Ingredient\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\"\xc1\x01\n" +
	"\fMealResponse\x12\x18\n" +
	"\aportion\x18\x01 \x01(\x05R\aportion\x12\x1d\n" +
	"\n" +
	"total_kcal\x18\x02 \x01(\x02R\ttotalKcal\x120\n" +
	"\x14cooking_time_minutes\x18\x03 \x01(\x05R\x12cookingTimeMinutes\x120\n" +
	"\vingredients\x18\x04 \x03(\v2\x0e.ai.IngredientR\vingredients\x12\x14\n" +
	"\x05steps\x18\x05 \x03(\tR\x05steps\"\x9c\x01\n" +
	"\x10NutritionRequest\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\x12\x19\n" +
	"\bavg_kcal\x18\x02 \x01(\x02R\aavgKcal\x12\x1f\n" +
	"\vavg_protein\x18\x03 \x01(\x02R\n" +
	"avgProtein\x12\x17\n" +
	"\aavg_fat\x18\x04 \x01(\x02R\x06avgFat\x12\x1b\n" +
	"\tavg_carbs\x18\x05 \x01(\x02R\bavgCarbs\"E\n" +
	"\x11NutritionResponse\x12\x1a\n" +
	"\bfeedback\x18\x01 \x01(\tR\bfeedback\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level2~\n" +
	"\tAiService\x120\n" +
	"\vAnalyzeMeal\x12\x0f.ai.MealRequest\x1a\x10.ai.MealResponse\x12?\n" +
	"\x10AnalyzeNutrition\x12\x14.ai.NutritionRequest\x1a\x15.ai.NutritionResponseB\x12Z\x10ai-service/protob\x06proto3"

var (
	file_ai_ai_proto_rawDescOnce sync.Once
	file_ai_ai_proto_rawDescData []byte
)

func file_ai_ai_proto_rawDescGZIP() []byte {
	file_ai_ai_proto_rawDescOnce.Do(func() {
		file_ai_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_ai_proto_rawDesc), len(file_ai_ai_proto_rawDesc)))
	})
	return file_ai_ai_proto_rawDescData
}

var file_ai_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ai_ai_proto_goTypes = []any{
	(*MealRequest)(nil),       // 0: ai.MealRequest
	(*Ingredient)(nil),        // 1: ai.Ingredient
	(*MealResponse)(nil),      // 2: ai.MealResponse
	(*NutritionRequest)(nil),  // 3: ai.NutritionRequest
	(*NutritionResponse)(nil), // 4: ai.NutritionResponse
}
var file_ai_ai_proto_depIdxs = []int32{
	1, // 0: ai.MealResponse.ingredients:type_name -> ai.Ingredient
	0, // 1: ai.AiService.AnalyzeMeal:input_type -> ai.MealRequest
	3, // 2: ai.AiService.AnalyzeNutrition:input_type -> ai.NutritionRequest
	2, // 3: ai.AiService.AnalyzeMeal:output_type -> ai.MealResponse
	4, // 4: ai.AiService.AnalyzeNutrition:output_type -> ai.NutritionResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ai_ai_proto_init() }
func file_ai_ai_proto_init() {
	if File_ai_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_ai_proto_rawDesc), len(file_ai_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_ai_proto_goTypes,
		DependencyIndexes: file_ai_ai_proto_depIdxs,
		MessageInfos:      file_ai_ai_proto_msgTypes,
	}.Build()
	File_ai_ai_proto = out.File
	file_ai_ai_proto_goTypes = nil
	file_ai_ai_proto_depIdxs = nil
}
