// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: statik/statik.proto

package nutritionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NutritionService_GetWeeklyNutrition_FullMethodName = "/nutrition.NutritionService/GetWeeklyNutrition"
)

// NutritionServiceClient is the client API for NutritionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =====================
// SERVICE
// =====================
type NutritionServiceClient interface {
	GetWeeklyNutrition(ctx context.Context, in *WeeklyNutritionRequest, opts ...grpc.CallOption) (*WeeklyNutritionResponse, error)
}

type nutritionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNutritionServiceClient(cc grpc.ClientConnInterface) NutritionServiceClient {
	return &nutritionServiceClient{cc}
}

func (c *nutritionServiceClient) GetWeeklyNutrition(ctx context.Context, in *WeeklyNutritionRequest, opts ...grpc.CallOption) (*WeeklyNutritionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WeeklyNutritionResponse)
	err := c.cc.Invoke(ctx, NutritionService_GetWeeklyNutrition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NutritionServiceServer is the server API for NutritionService service.
// All implementations must embed UnimplementedNutritionServiceServer
// for forward compatibility.
//
// =====================
// SERVICE
// =====================
type NutritionServiceServer interface {
	GetWeeklyNutrition(context.Context, *WeeklyNutritionRequest) (*WeeklyNutritionResponse, error)
	mustEmbedUnimplementedNutritionServiceServer()
}

// UnimplementedNutritionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNutritionServiceServer struct{}

func (UnimplementedNutritionServiceServer) GetWeeklyNutrition(context.Context, *WeeklyNutritionRequest) (*WeeklyNutritionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWeeklyNutrition not implemented")
}
func (UnimplementedNutritionServiceServer) mustEmbedUnimplementedNutritionServiceServer() {}
func (UnimplementedNutritionServiceServer) testEmbeddedByValue()                          {}

// UnsafeNutritionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NutritionServiceServer will
// result in compilation errors.
type UnsafeNutritionServiceServer interface {
	mustEmbedUnimplementedNutritionServiceServer()
}

func RegisterNutritionServiceServer(s grpc.ServiceRegistrar, srv NutritionServiceServer) {
	// If the following call panics, it indicates UnimplementedNutritionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NutritionService_ServiceDesc, srv)
}

func _NutritionService_GetWeeklyNutrition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WeeklyNutritionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NutritionServiceServer).GetWeeklyNutrition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NutritionService_GetWeeklyNutrition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NutritionServiceServer).GetWeeklyNutrition(ctx, req.(*WeeklyNutritionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NutritionService_ServiceDesc is the grpc.ServiceDesc for NutritionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NutritionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nutrition.NutritionService",
	HandlerType: (*NutritionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWeeklyNutrition",
			Handler:    _NutritionService_GetWeeklyNutrition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "statik/statik.proto",
}
