// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: statik/statik.proto

package nutritionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// =====================
// REQUEST
// =====================
type WeeklyNutritionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeeklyNutritionRequest) Reset() {
	*x = WeeklyNutritionRequest{}
	mi := &file_statik_statik_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeeklyNutritionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeeklyNutritionRequest) ProtoMessage() {}

func (x *WeeklyNutritionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statik_statik_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeeklyNutritionRequest.ProtoReflect.Descriptor instead.
func (*WeeklyNutritionRequest) Descriptor() ([]byte, []int) {
	return file_statik_statik_proto_rawDescGZIP(), []int{0}
}

func (x *WeeklyNutritionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// =====================
// RESPONSE
// =====================
type WeeklyNutritionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          []*DailyNutrition      `protobuf:"bytes,1,rep,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeeklyNutritionResponse) Reset() {
	*x = WeeklyNutritionResponse{}
	mi := &file_statik_statik_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeeklyNutritionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeeklyNutritionResponse) ProtoMessage() {}

func (x *WeeklyNutritionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statik_statik_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeeklyNutritionResponse.ProtoReflect.Descriptor instead.
func (*WeeklyNutritionResponse) Descriptor() ([]byte, []int) {
	return file_statik_statik_proto_rawDescGZIP(), []int{1}
}

func (x *WeeklyNutritionResponse) GetDays() []*DailyNutrition {
	if x != nil {
		return x.Days
	}
	return nil
}

// =====================
// DOMAIN MODEL
// =====================
type DailyNutrition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           string                 `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	Kcal          float64                `protobuf:"fixed64,2,opt,name=kcal,proto3" json:"kcal,omitempty"`
	Fat           float64                `protobuf:"fixed64,3,opt,name=fat,proto3" json:"fat,omitempty"`
	Carbs         float64                `protobuf:"fixed64,4,opt,name=carbs,proto3" json:"carbs,omitempty"`
	Protein       float64                `protobuf:"fixed64,5,opt,name=protein,proto3" json:"protein,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyNutrition) Reset() {
	*x = DailyNutrition{}
	mi := &file_statik_statik_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyNutrition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyNutrition) ProtoMessage() {}

func (x *DailyNutrition) ProtoReflect() protoreflect.Message {
	mi := &file_statik_statik_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyNutrition.ProtoReflect.Descriptor instead.
func (*DailyNutrition) Descriptor() ([]byte, []int) {
	return file_statik_statik_proto_rawDescGZIP(), []int{2}
}

func (x *DailyNutrition) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *DailyNutrition) GetKcal() float64 {
	if x != nil {
		return x.Kcal
	}
	return 0
}

func (x *DailyNutrition) GetFat() float64 {
	if x != nil {
		return x.Fat
	}
	return 0
}

func (x *DailyNutrition) GetCarbs() float64 {
	if x != nil {
		return x.Carbs
	}
	return 0
}

func (x *DailyNutrition) GetProtein() float64 {
	if x != nil {
		return x.Protein
	}
	return 0
}

var File_statik_statik_proto protoreflect.FileDescriptor

const file_statik_statik_proto_rawDesc = "" +
	"\n" +
	"\x13statik/statik.proto\x12\tnutrition\"1\n" +
	"\x16WeeklyNutritionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"H\n" +
	"\x17WeeklyNutritionResponse\x12-\n" +
	"\x04days\x18\x01 \x03(\v2\x19.nutrition.DailyNutritionR\x04days\"x\n" +
	"\x0eDailyNutrition\x12\x10\n" +
	"\x03day\x18\x01 \x01(\tR\x03day\x12\x12\n" +
	"\x04kcal\x18\x02 \x01(\x01R\x04kcal\x12\x10\n" +
	"\x03fat\x18\x03 \x01(\x01R\x03fat\x12\x14\n" +
	"\x05carbs\x18\x04 \x01(\x01R\x05carbs\x12\x18\n" +
	"\aprotein\x18\x05 \x01(\x01R\aprotein2o\n" +
	"\x10NutritionService\x12[\n" +
	"\x12GetWeeklyNutrition\x12!.nutrition.WeeklyNutritionRequest\x1a\".nutrition.WeeklyNutritionResponseB\x1dZ\x1bnutrition/proto;nutritionpbb\x06proto3"

var (
	file_statik_statik_proto_rawDescOnce sync.Once
	file_statik_statik_proto_rawDescData []byte
)

func file_statik_statik_proto_rawDescGZIP() []byte {
	file_statik_statik_proto_rawDescOnce.Do(func() {
		file_statik_statik_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_statik_statik_proto_rawDesc), len(file_statik_statik_proto_rawDesc)))
	})
	return file_statik_statik_proto_rawDescData
}

var file_statik_statik_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_statik_statik_proto_goTypes = []any{
	(*WeeklyNutritionRequest)(nil),  // 0: nutrition.WeeklyNutritionRequest
	(*WeeklyNutritionResponse)(nil), // 1: nutrition.WeeklyNutritionResponse
	(*DailyNutrition)(nil),          // 2: nutrition.DailyNutrition
}
var file_statik_statik_proto_depIdxs = []int32{
	2, // 0: nutrition.WeeklyNutritionResponse.days:type_name -> nutrition.DailyNutrition
	0, // 1: nutrition.NutritionService.GetWeeklyNutrition:input_type -> nutrition.WeeklyNutritionRequest
	1, // 2: nutrition.NutritionService.GetWeeklyNutrition:output_type -> nutrition.WeeklyNutritionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_statik_statik_proto_init() }
func file_statik_statik_proto_init() {
	if File_statik_statik_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_statik_statik_proto_rawDesc), len(file_statik_statik_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_statik_statik_proto_goTypes,
		DependencyIndexes: file_statik_statik_proto_depIdxs,
		MessageInfos:      file_statik_statik_proto_msgTypes,
	}.Build()
	File_statik_statik_proto = out.File
	file_statik_statik_proto_goTypes = nil
	file_statik_statik_proto_depIdxs = nil
}
