// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: food/food.proto

package food

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecipeService_CreateRecipe_FullMethodName  = "/food.RecipeService/CreateRecipe"
	RecipeService_GetRecipeByID_FullMethodName = "/food.RecipeService/GetRecipeByID"
	RecipeService_GetAllRecipes_FullMethodName = "/food.RecipeService/GetAllRecipes"
	RecipeService_UpdateRecipe_FullMethodName  = "/food.RecipeService/UpdateRecipe"
	RecipeService_DeleteRecipe_FullMethodName  = "/food.RecipeService/DeleteRecipe"
)

// RecipeServiceClient is the client API for RecipeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecipeServiceClient interface {
	CreateRecipe(ctx context.Context, in *CreateRecipeRequest, opts ...grpc.CallOption) (*Empty, error)
	GetRecipeByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*RecipeResponse, error)
	GetAllRecipes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RecipeListResponse, error)
	UpdateRecipe(ctx context.Context, in *UpdateRecipeRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteRecipe(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*Empty, error)
}

type recipeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecipeServiceClient(cc grpc.ClientConnInterface) RecipeServiceClient {
	return &recipeServiceClient{cc}
}

func (c *recipeServiceClient) CreateRecipe(ctx context.Context, in *CreateRecipeRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RecipeService_CreateRecipe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) GetRecipeByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*RecipeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecipeResponse)
	err := c.cc.Invoke(ctx, RecipeService_GetRecipeByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) GetAllRecipes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RecipeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecipeListResponse)
	err := c.cc.Invoke(ctx, RecipeService_GetAllRecipes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) UpdateRecipe(ctx context.Context, in *UpdateRecipeRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RecipeService_UpdateRecipe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) DeleteRecipe(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RecipeService_DeleteRecipe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecipeServiceServer is the server API for RecipeService service.
// All implementations must embed UnimplementedRecipeServiceServer
// for forward compatibility.
type RecipeServiceServer interface {
	CreateRecipe(context.Context, *CreateRecipeRequest) (*Empty, error)
	GetRecipeByID(context.Context, *GetByIDRequest) (*RecipeResponse, error)
	GetAllRecipes(context.Context, *Empty) (*RecipeListResponse, error)
	UpdateRecipe(context.Context, *UpdateRecipeRequest) (*Empty, error)
	DeleteRecipe(context.Context, *GetByIDRequest) (*Empty, error)
	mustEmbedUnimplementedRecipeServiceServer()
}

// UnimplementedRecipeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecipeServiceServer struct{}

func (UnimplementedRecipeServiceServer) CreateRecipe(context.Context, *CreateRecipeRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRecipe not implemented")
}
func (UnimplementedRecipeServiceServer) GetRecipeByID(context.Context, *GetByIDRequest) (*RecipeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecipeByID not implemented")
}
func (UnimplementedRecipeServiceServer) GetAllRecipes(context.Context, *Empty) (*RecipeListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllRecipes not implemented")
}
func (UnimplementedRecipeServiceServer) UpdateRecipe(context.Context, *UpdateRecipeRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRecipe not implemented")
}
func (UnimplementedRecipeServiceServer) DeleteRecipe(context.Context, *GetByIDRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRecipe not implemented")
}
func (UnimplementedRecipeServiceServer) mustEmbedUnimplementedRecipeServiceServer() {}
func (UnimplementedRecipeServiceServer) testEmbeddedByValue()                       {}

// UnsafeRecipeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecipeServiceServer will
// result in compilation errors.
type UnsafeRecipeServiceServer interface {
	mustEmbedUnimplementedRecipeServiceServer()
}

func RegisterRecipeServiceServer(s grpc.ServiceRegistrar, srv RecipeServiceServer) {
	// If the following call panics, it indicates UnimplementedRecipeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecipeService_ServiceDesc, srv)
}

func _RecipeService_CreateRecipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRecipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).CreateRecipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecipeService_CreateRecipe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).CreateRecipe(ctx, req.(*CreateRecipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_GetRecipeByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).GetRecipeByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecipeService_GetRecipeByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).GetRecipeByID(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_GetAllRecipes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).GetAllRecipes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecipeService_GetAllRecipes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).GetAllRecipes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_UpdateRecipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRecipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).UpdateRecipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecipeService_UpdateRecipe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).UpdateRecipe(ctx, req.(*UpdateRecipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_DeleteRecipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).DeleteRecipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecipeService_DeleteRecipe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).DeleteRecipe(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecipeService_ServiceDesc is the grpc.ServiceDesc for RecipeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecipeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "food.RecipeService",
	HandlerType: (*RecipeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRecipe",
			Handler:    _RecipeService_CreateRecipe_Handler,
		},
		{
			MethodName: "GetRecipeByID",
			Handler:    _RecipeService_GetRecipeByID_Handler,
		},
		{
			MethodName: "GetAllRecipes",
			Handler:    _RecipeService_GetAllRecipes_Handler,
		},
		{
			MethodName: "UpdateRecipe",
			Handler:    _RecipeService_UpdateRecipe_Handler,
		},
		{
			MethodName: "DeleteRecipe",
			Handler:    _RecipeService_DeleteRecipe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "food/food.proto",
}

const (
	SaladService_CreateSalad_FullMethodName  = "/food.SaladService/CreateSalad"
	SaladService_GetSaladByID_FullMethodName = "/food.SaladService/GetSaladByID"
	SaladService_GetAllSalads_FullMethodName = "/food.SaladService/GetAllSalads"
	SaladService_UpdateSalad_FullMethodName  = "/food.SaladService/UpdateSalad"
	SaladService_DeleteSalad_FullMethodName  = "/food.SaladService/DeleteSalad"
)

// SaladServiceClient is the client API for SaladService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SaladServiceClient interface {
	CreateSalad(ctx context.Context, in *CreateSaladRequest, opts ...grpc.CallOption) (*Empty, error)
	GetSaladByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*SaladResponse, error)
	GetAllSalads(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SaladListResponse, error)
	UpdateSalad(ctx context.Context, in *UpdateSaladRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteSalad(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*Empty, error)
}

type saladServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSaladServiceClient(cc grpc.ClientConnInterface) SaladServiceClient {
	return &saladServiceClient{cc}
}

func (c *saladServiceClient) CreateSalad(ctx context.Context, in *CreateSaladRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SaladService_CreateSalad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saladServiceClient) GetSaladByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*SaladResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaladResponse)
	err := c.cc.Invoke(ctx, SaladService_GetSaladByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saladServiceClient) GetAllSalads(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SaladListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaladListResponse)
	err := c.cc.Invoke(ctx, SaladService_GetAllSalads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saladServiceClient) UpdateSalad(ctx context.Context, in *UpdateSaladRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SaladService_UpdateSalad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saladServiceClient) DeleteSalad(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SaladService_DeleteSalad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SaladServiceServer is the server API for SaladService service.
// All implementations must embed UnimplementedSaladServiceServer
// for forward compatibility.
type SaladServiceServer interface {
	CreateSalad(context.Context, *CreateSaladRequest) (*Empty, error)
	GetSaladByID(context.Context, *GetByIDRequest) (*SaladResponse, error)
	GetAllSalads(context.Context, *Empty) (*SaladListResponse, error)
	UpdateSalad(context.Context, *UpdateSaladRequest) (*Empty, error)
	DeleteSalad(context.Context, *GetByIDRequest) (*Empty, error)
	mustEmbedUnimplementedSaladServiceServer()
}

// UnimplementedSaladServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSaladServiceServer struct{}

func (UnimplementedSaladServiceServer) CreateSalad(context.Context, *CreateSaladRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSalad not implemented")
}
func (UnimplementedSaladServiceServer) GetSaladByID(context.Context, *GetByIDRequest) (*SaladResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSaladByID not implemented")
}
func (UnimplementedSaladServiceServer) GetAllSalads(context.Context, *Empty) (*SaladListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllSalads not implemented")
}
func (UnimplementedSaladServiceServer) UpdateSalad(context.Context, *UpdateSaladRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSalad not implemented")
}
func (UnimplementedSaladServiceServer) DeleteSalad(context.Context, *GetByIDRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSalad not implemented")
}
func (UnimplementedSaladServiceServer) mustEmbedUnimplementedSaladServiceServer() {}
func (UnimplementedSaladServiceServer) testEmbeddedByValue()                      {}

// UnsafeSaladServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SaladServiceServer will
// result in compilation errors.
type UnsafeSaladServiceServer interface {
	mustEmbedUnimplementedSaladServiceServer()
}

func RegisterSaladServiceServer(s grpc.ServiceRegistrar, srv SaladServiceServer) {
	// If the following call panics, it indicates UnimplementedSaladServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SaladService_ServiceDesc, srv)
}

func _SaladService_CreateSalad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSaladRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaladServiceServer).CreateSalad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SaladService_CreateSalad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaladServiceServer).CreateSalad(ctx, req.(*CreateSaladRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SaladService_GetSaladByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaladServiceServer).GetSaladByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SaladService_GetSaladByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaladServiceServer).GetSaladByID(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SaladService_GetAllSalads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaladServiceServer).GetAllSalads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SaladService_GetAllSalads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaladServiceServer).GetAllSalads(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SaladService_UpdateSalad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSaladRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaladServiceServer).UpdateSalad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SaladService_UpdateSalad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaladServiceServer).UpdateSalad(ctx, req.(*UpdateSaladRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SaladService_DeleteSalad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaladServiceServer).DeleteSalad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SaladService_DeleteSalad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaladServiceServer).DeleteSalad(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SaladService_ServiceDesc is the grpc.ServiceDesc for SaladService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SaladService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "food.SaladService",
	HandlerType: (*SaladServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSalad",
			Handler:    _SaladService_CreateSalad_Handler,
		},
		{
			MethodName: "GetSaladByID",
			Handler:    _SaladService_GetSaladByID_Handler,
		},
		{
			MethodName: "GetAllSalads",
			Handler:    _SaladService_GetAllSalads_Handler,
		},
		{
			MethodName: "UpdateSalad",
			Handler:    _SaladService_UpdateSalad_Handler,
		},
		{
			MethodName: "DeleteSalad",
			Handler:    _SaladService_DeleteSalad_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "food/food.proto",
}

const (
	RestaurantService_CreateRestaurant_FullMethodName  = "/food.RestaurantService/CreateRestaurant"
	RestaurantService_GetRestaurantByID_FullMethodName = "/food.RestaurantService/GetRestaurantByID"
	RestaurantService_GetAllRestaurants_FullMethodName = "/food.RestaurantService/GetAllRestaurants"
	RestaurantService_UpdateRestaurant_FullMethodName  = "/food.RestaurantService/UpdateRestaurant"
	RestaurantService_DeleteRestaurant_FullMethodName  = "/food.RestaurantService/DeleteRestaurant"
)

// RestaurantServiceClient is the client API for RestaurantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestaurantServiceClient interface {
	CreateRestaurant(ctx context.Context, in *CreateRestaurantRequest, opts ...grpc.CallOption) (*CreateRestaurantResponse, error)
	GetRestaurantByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*RestaurantResponse, error)
	GetAllRestaurants(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RestaurantListResponse, error)
	UpdateRestaurant(ctx context.Context, in *UpdateRestaurantRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteRestaurant(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*Empty, error)
}

type restaurantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRestaurantServiceClient(cc grpc.ClientConnInterface) RestaurantServiceClient {
	return &restaurantServiceClient{cc}
}

func (c *restaurantServiceClient) CreateRestaurant(ctx context.Context, in *CreateRestaurantRequest, opts ...grpc.CallOption) (*CreateRestaurantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRestaurantResponse)
	err := c.cc.Invoke(ctx, RestaurantService_CreateRestaurant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) GetRestaurantByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*RestaurantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestaurantResponse)
	err := c.cc.Invoke(ctx, RestaurantService_GetRestaurantByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) GetAllRestaurants(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RestaurantListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestaurantListResponse)
	err := c.cc.Invoke(ctx, RestaurantService_GetAllRestaurants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) UpdateRestaurant(ctx context.Context, in *UpdateRestaurantRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RestaurantService_UpdateRestaurant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) DeleteRestaurant(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RestaurantService_DeleteRestaurant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestaurantServiceServer is the server API for RestaurantService service.
// All implementations must embed UnimplementedRestaurantServiceServer
// for forward compatibility.
type RestaurantServiceServer interface {
	CreateRestaurant(context.Context, *CreateRestaurantRequest) (*CreateRestaurantResponse, error)
	GetRestaurantByID(context.Context, *GetByIDRequest) (*RestaurantResponse, error)
	GetAllRestaurants(context.Context, *Empty) (*RestaurantListResponse, error)
	UpdateRestaurant(context.Context, *UpdateRestaurantRequest) (*Empty, error)
	DeleteRestaurant(context.Context, *GetByIDRequest) (*Empty, error)
	mustEmbedUnimplementedRestaurantServiceServer()
}

// UnimplementedRestaurantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRestaurantServiceServer struct{}

func (UnimplementedRestaurantServiceServer) CreateRestaurant(context.Context, *CreateRestaurantRequest) (*CreateRestaurantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRestaurant not implemented")
}
func (UnimplementedRestaurantServiceServer) GetRestaurantByID(context.Context, *GetByIDRequest) (*RestaurantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRestaurantByID not implemented")
}
func (UnimplementedRestaurantServiceServer) GetAllRestaurants(context.Context, *Empty) (*RestaurantListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllRestaurants not implemented")
}
func (UnimplementedRestaurantServiceServer) UpdateRestaurant(context.Context, *UpdateRestaurantRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRestaurant not implemented")
}
func (UnimplementedRestaurantServiceServer) DeleteRestaurant(context.Context, *GetByIDRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRestaurant not implemented")
}
func (UnimplementedRestaurantServiceServer) mustEmbedUnimplementedRestaurantServiceServer() {}
func (UnimplementedRestaurantServiceServer) testEmbeddedByValue()                           {}

// UnsafeRestaurantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestaurantServiceServer will
// result in compilation errors.
type UnsafeRestaurantServiceServer interface {
	mustEmbedUnimplementedRestaurantServiceServer()
}

func RegisterRestaurantServiceServer(s grpc.ServiceRegistrar, srv RestaurantServiceServer) {
	// If the following call panics, it indicates UnimplementedRestaurantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RestaurantService_ServiceDesc, srv)
}

func _RestaurantService_CreateRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRestaurantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).CreateRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantService_CreateRestaurant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).CreateRestaurant(ctx, req.(*CreateRestaurantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_GetRestaurantByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).GetRestaurantByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantService_GetRestaurantByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).GetRestaurantByID(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_GetAllRestaurants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).GetAllRestaurants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantService_GetAllRestaurants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).GetAllRestaurants(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_UpdateRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRestaurantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).UpdateRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantService_UpdateRestaurant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).UpdateRestaurant(ctx, req.(*UpdateRestaurantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_DeleteRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).DeleteRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantService_DeleteRestaurant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).DeleteRestaurant(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RestaurantService_ServiceDesc is the grpc.ServiceDesc for RestaurantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RestaurantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "food.RestaurantService",
	HandlerType: (*RestaurantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRestaurant",
			Handler:    _RestaurantService_CreateRestaurant_Handler,
		},
		{
			MethodName: "GetRestaurantByID",
			Handler:    _RestaurantService_GetRestaurantByID_Handler,
		},
		{
			MethodName: "GetAllRestaurants",
			Handler:    _RestaurantService_GetAllRestaurants_Handler,
		},
		{
			MethodName: "UpdateRestaurant",
			Handler:    _RestaurantService_UpdateRestaurant_Handler,
		},
		{
			MethodName: "DeleteRestaurant",
			Handler:    _RestaurantService_DeleteRestaurant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "food/food.proto",
}

const (
	FoodFilterService_FilterFood_FullMethodName = "/food.FoodFilterService/FilterFood"
)

// FoodFilterServiceClient is the client API for FoodFilterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FoodFilterServiceClient interface {
	FilterFood(ctx context.Context, in *FoodFilterRequest, opts ...grpc.CallOption) (*FoodListResponse, error)
}

type foodFilterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFoodFilterServiceClient(cc grpc.ClientConnInterface) FoodFilterServiceClient {
	return &foodFilterServiceClient{cc}
}

func (c *foodFilterServiceClient) FilterFood(ctx context.Context, in *FoodFilterRequest, opts ...grpc.CallOption) (*FoodListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FoodListResponse)
	err := c.cc.Invoke(ctx, FoodFilterService_FilterFood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FoodFilterServiceServer is the server API for FoodFilterService service.
// All implementations must embed UnimplementedFoodFilterServiceServer
// for forward compatibility.
type FoodFilterServiceServer interface {
	FilterFood(context.Context, *FoodFilterRequest) (*FoodListResponse, error)
	mustEmbedUnimplementedFoodFilterServiceServer()
}

// UnimplementedFoodFilterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFoodFilterServiceServer struct{}

func (UnimplementedFoodFilterServiceServer) FilterFood(context.Context, *FoodFilterRequest) (*FoodListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FilterFood not implemented")
}
func (UnimplementedFoodFilterServiceServer) mustEmbedUnimplementedFoodFilterServiceServer() {}
func (UnimplementedFoodFilterServiceServer) testEmbeddedByValue()                           {}

// UnsafeFoodFilterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FoodFilterServiceServer will
// result in compilation errors.
type UnsafeFoodFilterServiceServer interface {
	mustEmbedUnimplementedFoodFilterServiceServer()
}

func RegisterFoodFilterServiceServer(s grpc.ServiceRegistrar, srv FoodFilterServiceServer) {
	// If the following call panics, it indicates UnimplementedFoodFilterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FoodFilterService_ServiceDesc, srv)
}

func _FoodFilterService_FilterFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FoodFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodFilterServiceServer).FilterFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FoodFilterService_FilterFood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodFilterServiceServer).FilterFood(ctx, req.(*FoodFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FoodFilterService_ServiceDesc is the grpc.ServiceDesc for FoodFilterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FoodFilterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "food.FoodFilterService",
	HandlerType: (*FoodFilterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FilterFood",
			Handler:    _FoodFilterService_FilterFood_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "food/food.proto",
}
