// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: food/food.proto

package food

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_food_food_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_food_food_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_food_food_proto_rawDescGZIP(), []int{0}
}

type GetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDRequest) Reset() {
	*x = GetByIDRequest{}
	mi := &file_food_food_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDRequest) ProtoMessage() {}

func (x *GetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_food_food_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return file_food_food_proto_rawDescGZIP(), []int{1}
}

func (x *GetByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Recipe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RestaurantId  int64                  `protobuf:"varint,2,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,6,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	Country       string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	MealTime      string                 `protobuf:"bytes,8,opt,name=meal_time,json=mealTime,proto3" json:"meal_time,omitempty"`
	Kcal          int32                  `protobuf:"varint,9,opt,name=kcal,proto3" json:"kcal,omitempty"`
	Protein       float64                `protobuf:"fixed64,10,opt,name=protein,proto3" json:"protein,omitempty"`
	Fat           float64                `protobuf:"fixed64,11,opt,name=fat,proto3" json:"fat,omitempty"`
	Carbs         float64                `protobuf:"fixed64,12,opt,name=carbs,proto3" json:"carbs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recipe) Reset() {
	*x = Recipe{}
	mi := &file_food_food_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recipe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipe) ProtoMessage() {}

func (x *Recipe) ProtoReflect() protoreflect.Message {
	mi := &file_food_food_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipe.ProtoReflect.Descriptor instead.
func (*Recipe) Descriptor() ([]byte, []int) {
	return file_food_food_proto_rawDescGZIP(), []int{2}
}

func (x *Recipe) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Recipe) GetRestaurantId() int64 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *Recipe) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Recipe) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Recipe) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Recipe) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *Recipe) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Recipe) GetMealTime() string {
	if x != nil {
		return x.MealTime
	}
	return ""
}

func (x *Recipe) GetKcal() int32 {
	if x != nil {
		return x.Kcal
	}
	return 0
}

func (x *Recipe) GetProtein() float64 {
	if x != nil {
		return x.Protein
	}
	return 0
}

func (x *Recipe) GetFat() float64 {
	if x != nil {
		return x.Fat
	}
	return 0
}

func (x *Recipe) GetCarbs() float64 {
	if x != nil {
		return x.Carbs
	}
	return 0
}

type CreateRecipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipe        *Recipe                `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecipeRequest) Reset() {
	*x = CreateRecipeRequest{}
	mi := &file_food_food_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecipeRequest) ProtoMessage() {}

func (x *CreateRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_food_food_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecipeRequest.ProtoReflect.Descriptor instead.
func (*CreateRecipeRequest) Descriptor() ([]byte, []int) {
	return file_food_food_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRecipeRequest) GetRecipe() *Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

type UpdateRecipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipe        *Recipe                `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecipeRequest) Reset() {
	*x = UpdateRecipeRequest{}
	mi := &file_food_food_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecipeRequest) ProtoMessage() {}

func (x *UpdateRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_food_food_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecipeRequest.ProtoReflect.Descriptor instead.
func (*UpdateRecipeRequest) Descriptor() ([]byte, []int) {
	return file_food_food_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRecipeRequest) GetRecipe() *Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

type RecipeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipe        *Recipe                `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipeResponse) Reset() {
	*x = RecipeResponse{}
	mi := &file_food_food_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeResponse) ProtoMessage() {}

func (x *RecipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_food_food_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeResponse.ProtoReflect.Descriptor instead.
func (*RecipeResponse) Descriptor() ([]byte, []int) {
	return file_food_food_proto_rawDescGZIP(), []int{5}
}

func (x *RecipeResponse) GetRecipe() *Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

type RecipeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipes       []*Recipe              `protobuf:"bytes,1,rep,name=recipes,proto3" json:"recipes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipeListResponse) Reset() {
	*x = RecipeListResponse{}
	mi := &file_food_food_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeListResponse) ProtoMessage() {}

func (x *RecipeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_food_food_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeListResponse.ProtoReflect.Descriptor instead.
func (*RecipeListResponse) Descriptor() ([]byte, []int) {
	return file_food_food_proto_rawDescGZIP(), []int{6}
}

func (x *RecipeListResponse) GetRecipes() []*Recipe {
	if x != nil {
		return x.Recipes
	}
	return nil
}

type Salad struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RestaurantId  int64                  `protobuf:"varint,2,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,6,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	Country       string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	MealTime      string                 `protobuf:"bytes,8,opt,name=meal_time,json=mealTime,proto3" json:"meal_time,omitempty"`
	Kcal          int32                  `protobuf:"varint,9,opt,name=kcal,proto3" json:"kcal,omitempty"`
	Protein       float64                `protobuf:"fixed64,10,opt,name=protein,proto3" json:"protein,omitempty"`
	Fat           float64                `protobuf:"fixed64,11,opt,name=fat,proto3" json:"fat,omitempty"`
	Carbs         float64                `protobuf:"fixed64,12,opt,name=carbs,proto3" json:"carbs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Salad) Reset() {
	*x = Salad{}
	mi := &file_food_food_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Salad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Salad) ProtoMessage() {}

func (x *Salad) ProtoReflect() protoreflect.Message {
	mi := &file_food_food_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Salad.ProtoReflect.Descriptor instead.
func (*Salad) Descriptor() ([]byte, []int) {
	return file_food_food_proto_rawDescGZIP(), []int{7}
}

func (x *Salad) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Salad) GetRestaurantId() int64 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *Salad) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Salad) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Salad) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Salad) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *Salad) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Salad) GetMealTime() string {
	if x != nil {
		return x.MealTime
	}
	return ""
}

func (x *Salad) GetKcal() int32 {
	if x != nil {
		return x.Kcal
	}
	return 0
}

func (x *Salad) GetProtein() float64 {
	if x != nil {
		return x.Protein
	}
	return 0
}

func (x *Salad) GetFat() float64 {
	if x != nil {
		return x.Fat
	}
	return 0
}

func (x *Salad) GetCarbs() float64 {
	if x != nil {
		return x.Carbs
	}
	return 0
}

type CreateSaladRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Salad         *Salad                 `protobuf:"bytes,1,opt,name=salad,proto3" json:"salad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSaladRequest) Reset() {
	*x = CreateSaladRequest{}
	mi := &file_food_food_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSaladRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSaladRequest) ProtoMessage() {}

func (x *CreateSaladRequest) ProtoReflect() protoreflect.Message {
	mi := &file_food_food_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSaladRequest.ProtoReflect.Descriptor instead.
func (*CreateSaladRequest) Descriptor() ([]byte, []int) {
	return file_food_food_proto_rawDescGZIP(), []int{8}
}

func (x *CreateSaladRequest) GetSalad() *Salad {
	if x != nil {
		return x.Salad
	}
	return nil
}

type UpdateSaladRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Salad         *Salad                 `protobuf:"bytes,1,opt,name=salad,proto3" json:"salad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSaladRequest) Reset() {
	*x = UpdateSaladRequest{}
	mi := &file_food_food_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSaladRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSaladRequest) ProtoMessage() {}

func (x *UpdateSaladRequest) ProtoReflect() protoreflect.Message {
	mi := &file_food_food_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSaladRequest.ProtoReflect.Descriptor instead.
func (*UpdateSaladRequest) Descriptor() ([]byte, []int) {
	return file_food_food_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateSaladRequest) GetSalad() *Salad {
	if x != nil {
		return x.Salad
	}
	return nil
}

type SaladResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Salad         *Salad                 `protobuf:"bytes,1,opt,name=salad,proto3" json:"salad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaladResponse) Reset() {
	*x = SaladResponse{}
	mi := &file_food_food_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaladResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaladResponse) ProtoMessage() {}

func (x *SaladResponse) ProtoReflect() protoreflect.Message {
	mi := &file_food_food_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaladResponse.ProtoReflect.Descriptor instead.
func (*SaladResponse) Descriptor() ([]byte, []int) {
	return file_food_food_proto_rawDescGZIP(), []int{10}
}

func (x *SaladResponse) GetSalad() *Salad {
	if x != nil {
		return x.Salad
	}
	return nil
}

type SaladListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Salads        []*Salad               `protobuf:"bytes,1,rep,name=salads,proto3" json:"salads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaladListResponse) Reset() {
	*x = SaladListResponse{}
	mi := &file_food_food_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaladListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaladListResponse) ProtoMessage() {}

func (x *SaladListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_food_food_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaladListResponse.ProtoReflect.Descriptor instead.
func (*SaladListResponse) Descriptor() ([]byte, []int) {
	return file_food_food_proto_rawDescGZIP(), []int{11}
}

func (x *SaladListResponse) GetSalads() []*Salad {
	if x != nil {
		return x.Salads
	}
	return nil
}

type Restaurant struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RestaurantName string                 `protobuf:"bytes,2,opt,name=restaurant_name,json=restaurantName,proto3" json:"restaurant_name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl       string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Restaurant) Reset() {
	*x = Restaurant{}
	mi := &file_food_food_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Restaurant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restaurant) ProtoMessage() {}

func (x *Restaurant) ProtoReflect() protoreflect.Message {
	mi := &file_food_food_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restaurant.ProtoReflect.Descriptor instead.
func (*Restaurant) Descriptor() ([]byte, []int) {
	return file_food_food_proto_rawDescGZIP(), []int{12}
}

func (x *Restaurant) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Restaurant) GetRestaurantName() string {
	if x != nil {
		return x.RestaurantName
	}
	return ""
}

func (x *Restaurant) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Restaurant) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type CreateRestaurantRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RestaurantName string                 `protobuf:"bytes,1,opt,name=restaurant_name,json=restaurantName,proto3" json:"restaurant_name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl       string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateRestaurantRequest) Reset() {
	*x = CreateRestaurantRequest{}
	mi := &file_food_food_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRestaurantRequest) ProtoMessage() {}

func (x *CreateRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_food_food_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRestaurantRequest.ProtoReflect.Descriptor instead.
func (*CreateRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_food_food_proto_rawDescGZIP(), []int{13}
}

func (x *CreateRestaurantRequest) GetRestaurantName() string {
	if x != nil {
		return x.RestaurantName
	}
	return ""
}

func (x *CreateRestaurantRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRestaurantRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type CreateRestaurantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRestaurantResponse) Reset() {
	*x = CreateRestaurantResponse{}
	mi := &file_food_food_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRestaurantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRestaurantResponse) ProtoMessage() {}

func (x *CreateRestaurantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_food_food_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRestaurantResponse.ProtoReflect.Descriptor instead.
func (*CreateRestaurantResponse) Descriptor() ([]byte, []int) {
	return file_food_food_proto_rawDescGZIP(), []int{14}
}

func (x *CreateRestaurantResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateRestaurantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restaurant    *Restaurant            `protobuf:"bytes,1,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRestaurantRequest) Reset() {
	*x = UpdateRestaurantRequest{}
	mi := &file_food_food_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRestaurantRequest) ProtoMessage() {}

func (x *UpdateRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_food_food_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRestaurantRequest.ProtoReflect.Descriptor instead.
func (*UpdateRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_food_food_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateRestaurantRequest) GetRestaurant() *Restaurant {
	if x != nil {
		return x.Restaurant
	}
	return nil
}

type RestaurantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restaurant    *Restaurant            `protobuf:"bytes,1,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantResponse) Reset() {
	*x = RestaurantResponse{}
	mi := &file_food_food_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantResponse) ProtoMessage() {}

func (x *RestaurantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_food_food_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantResponse.ProtoReflect.Descriptor instead.
func (*RestaurantResponse) Descriptor() ([]byte, []int) {
	return file_food_food_proto_rawDescGZIP(), []int{16}
}

func (x *RestaurantResponse) GetRestaurant() *Restaurant {
	if x != nil {
		return x.Restaurant
	}
	return nil
}

type RestaurantListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restaurants   []*Restaurant          `protobuf:"bytes,1,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantListResponse) Reset() {
	*x = RestaurantListResponse{}
	mi := &file_food_food_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantListResponse) ProtoMessage() {}

func (x *RestaurantListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_food_food_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantListResponse.ProtoReflect.Descriptor instead.
func (*RestaurantListResponse) Descriptor() ([]byte, []int) {
	return file_food_food_proto_rawDescGZIP(), []int{17}
}

func (x *RestaurantListResponse) GetRestaurants() []*Restaurant {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

type FoodFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	MealTime      string                 `protobuf:"bytes,2,opt,name=meal_time,json=mealTime,proto3" json:"meal_time,omitempty"`
	MaxKcal       int32                  `protobuf:"varint,3,opt,name=max_kcal,json=maxKcal,proto3" json:"max_kcal,omitempty"`
	IncludeSalads bool                   `protobuf:"varint,4,opt,name=include_salads,json=includeSalads,proto3" json:"include_salads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodFilterRequest) Reset() {
	*x = FoodFilterRequest{}
	mi := &file_food_food_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodFilterRequest) ProtoMessage() {}

func (x *FoodFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_food_food_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodFilterRequest.ProtoReflect.Descriptor instead.
func (*FoodFilterRequest) Descriptor() ([]byte, []int) {
	return file_food_food_proto_rawDescGZIP(), []int{18}
}

func (x *FoodFilterRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *FoodFilterRequest) GetMealTime() string {
	if x != nil {
		return x.MealTime
	}
	return ""
}

func (x *FoodFilterRequest) GetMaxKcal() int32 {
	if x != nil {
		return x.MaxKcal
	}
	return 0
}

func (x *FoodFilterRequest) GetIncludeSalads() bool {
	if x != nil {
		return x.IncludeSalads
	}
	return false
}

type FoodItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // recipe | salad
	RestaurantId  int64                  `protobuf:"varint,3,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,7,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	Country       string                 `protobuf:"bytes,8,opt,name=country,proto3" json:"country,omitempty"`
	MealTime      string                 `protobuf:"bytes,9,opt,name=meal_time,json=mealTime,proto3" json:"meal_time,omitempty"`
	Kcal          int32                  `protobuf:"varint,10,opt,name=kcal,proto3" json:"kcal,omitempty"`
	Protein       float64                `protobuf:"fixed64,11,opt,name=protein,proto3" json:"protein,omitempty"`
	Fat           float64                `protobuf:"fixed64,12,opt,name=fat,proto3" json:"fat,omitempty"`
	Carbs         float64                `protobuf:"fixed64,13,opt,name=carbs,proto3" json:"carbs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodItem) Reset() {
	*x = FoodItem{}
	mi := &file_food_food_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodItem) ProtoMessage() {}

func (x *FoodItem) ProtoReflect() protoreflect.Message {
	mi := &file_food_food_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodItem.ProtoReflect.Descriptor instead.
func (*FoodItem) Descriptor() ([]byte, []int) {
	return file_food_food_proto_rawDescGZIP(), []int{19}
}

func (x *FoodItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FoodItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FoodItem) GetRestaurantId() int64 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *FoodItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FoodItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FoodItem) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *FoodItem) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *FoodItem) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *FoodItem) GetMealTime() string {
	if x != nil {
		return x.MealTime
	}
	return ""
}

func (x *FoodItem) GetKcal() int32 {
	if x != nil {
		return x.Kcal
	}
	return 0
}

func (x *FoodItem) GetProtein() float64 {
	if x != nil {
		return x.Protein
	}
	return 0
}

func (x *FoodItem) GetFat() float64 {
	if x != nil {
		return x.Fat
	}
	return 0
}

func (x *FoodItem) GetCarbs() float64 {
	if x != nil {
		return x.Carbs
	}
	return 0
}

type FoodListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FoodItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodListResponse) Reset() {
	*x = FoodListResponse{}
	mi := &file_food_food_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodListResponse) ProtoMessage() {}

func (x *FoodListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_food_food_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodListResponse.ProtoReflect.Descriptor instead.
func (*FoodListResponse) Descriptor() ([]byte, []int) {
	return file_food_food_proto_rawDescGZIP(), []int{20}
}

func (x *FoodListResponse) GetItems() []*FoodItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_food_food_proto protoreflect.FileDescriptor

const file_food_food_proto_rawDesc = "" +
	"\n" +
	"\x0ffood/food.proto\x12\x04food\"\a\n" +
	"\x05Empty\" \n" +
	"\x0eGetByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xba\x02\n" +
	"\x06Recipe\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rrestaurant_id\x18\x02 \x01(\x03R\frestaurantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tvideo_url\x18\x06 \x01(\tR\bvideoUrl\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12\x1b\n" +
	"\tmeal_time\x18\b \x01(\tR\bmealTime\x12\x12\n" +
	"\x04kcal\x18\t \x01(\x05R\x04kcal\x12\x18\n" +
	"\aprotein\x18\n" +
	" \x01(\x01R\aprotein\x12\x10\n" +
	"\x03fat\x18\v \x01(\x01R\x03fat\x12\x14\n" +
	"\x05carbs\x18\f \x01(\x01R\x05carbs\";\n" +
	"\x13CreateRecipeRequest\x12$\n" +
	"\x06recipe\x18\x01 \x01(\v2\f.food.RecipeR\x06recipe\";\n" +
	"\x13UpdateRecipeRequest\x12$\n" +
	"\x06recipe\x18\x01 \x01(\v2\f.food.RecipeR\x06recipe\"6\n" +
	"\x0eRecipeResponse\x12$\n" +
	"\x06recipe\x18\x01 \x01(\v2\f.food.RecipeR\x06recipe\"<\n" +
	"\x12RecipeListResponse\x12&\n" +
	"\arecipes\x18\x01 \x03(\v2\f.food.RecipeR\arecipes\"\xb9\x02\n" +
	"\x05Salad\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rrestaurant_id\x18\x02 \x01(\x03R\frestaurantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tvideo_url\x18\x06 \x01(\tR\bvideoUrl\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12\x1b\n" +
	"\tmeal_time\x18\b \x01(\tR\bmealTime\x12\x12\n" +
	"\x04kcal\x18\t \x01(\x05R\x04kcal\x12\x18\n" +
	"\aprotein\x18\n" +
	" \x01(\x01R\aprotein\x12\x10\n" +
	"\x03fat\x18\v \x01(\x01R\x03fat\x12\x14\n" +
	"\x05carbs\x18\f \x01(\x01R\x05carbs\"7\n" +
	"\x12CreateSaladRequest\x12!\n" +
	"\x05salad\x18\x01 \x01(\v2\v.food.SaladR\x05salad\"7\n" +
	"\x12UpdateSaladRequest\x12!\n" +
	"\x05salad\x18\x01 \x01(\v2\v.food.SaladR\x05salad\"2\n" +
	"\rSaladResponse\x12!\n" +
	"\x05salad\x18\x01 \x01(\v2\v.food.SaladR\x05salad\"8\n" +
	"\x11SaladListResponse\x12#\n" +
	"\x06salads\x18\x01 \x03(\v2\v.food.SaladR\x06salads\"\x84\x01\n" +
	"\n" +
	"Restaurant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12'\n" +
	"\x0frestaurant_name\x18\x02 \x01(\tR\x0erestaurantName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\"\x81\x01\n" +
	"\x17CreateRestaurantRequest\x12'\n" +
	"\x0frestaurant_name\x18\x01 \x01(\tR\x0erestaurantName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\"*\n" +
	"\x18CreateRestaurantResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"K\n" +
	"\x17UpdateRestaurantRequest\x120\n" +
	"\n" +
	"restaurant\x18\x01 \x01(\v2\x10.food.RestaurantR\n" +
	"restaurant\"F\n" +
	"\x12RestaurantResponse\x120\n" +
	"\n" +
	"restaurant\x18\x01 \x01(\v2\x10.food.RestaurantR\n" +
	"restaurant\"L\n" +
	"\x16RestaurantListResponse\x122\n" +
	"\vrestaurants\x18\x01 \x03(\v2\x10.food.RestaurantR\vrestaurants\"\x8c\x01\n" +
	"\x11FoodFilterRequest\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x1b\n" +
	"\tmeal_time\x18\x02 \x01(\tR\bmealTime\x12\x19\n" +
	"\bmax_kcal\x18\x03 \x01(\x05R\amaxKcal\x12%\n" +
	"\x0einclude_salads\x18\x04 \x01(\bR\rincludeSalads\"\xd0\x02\n" +
	"\bFoodItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12#\n" +
	"\rrestaurant_id\x18\x03 \x01(\x03R\frestaurantId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tvideo_url\x18\a \x01(\tR\bvideoUrl\x12\x18\n" +
	"\acountry\x18\b \x01(\tR\acountry\x12\x1b\n" +
	"\tmeal_time\x18\t \x01(\tR\bmealTime\x12\x12\n" +
	"\x04kcal\x18\n" +
	" \x01(\x05R\x04kcal\x12\x18\n" +
	"\aprotein\x18\v \x01(\x01R\aprotein\x12\x10\n" +
	"\x03fat\x18\f \x01(\x01R\x03fat\x12\x14\n" +
	"\x05carbs\x18\r \x01(\x01R\x05carbs\"8\n" +
	"\x10FoodListResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.food.FoodItemR\x05items2\xa7\x02\n" +
	"\rRecipeService\x126\n" +
	"\fCreateRecipe\x12\x19.food.CreateRecipeRequest\x1a\v.food.Empty\x12;\n" +
	"\rGetRecipeByID\x12\x14.food.GetByIDRequest\x1a\x14.food.RecipeResponse\x126\n" +
	"\rGetAllRecipes\x12\v.food.Empty\x1a\x18.food.RecipeListResponse\x126\n" +
	"\fUpdateRecipe\x12\x19.food.UpdateRecipeRequest\x1a\v.food.Empty\x121\n" +
	"\fDeleteRecipe\x12\x14.food.GetByIDRequest\x1a\v.food.Empty2\x9d\x02\n" +
	"\fSaladService\x124\n" +
	"\vCreateSalad\x12\x18.food.CreateSaladRequest\x1a\v.food.Empty\x129\n" +
	"\fGetSaladByID\x12\x14.food.GetByIDRequest\x1a\x13.food.SaladResponse\x124\n" +
	"\fGetAllSalads\x12\v.food.Empty\x1a\x17.food.SaladListResponse\x124\n" +
	"\vUpdateSalad\x12\x18.food.UpdateSaladRequest\x1a\v.food.Empty\x120\n" +
	"\vDeleteSalad\x12\x14.food.GetByIDRequest\x1a\v.food.Empty2\xe2\x02\n" +
	"\x11RestaurantService\x12Q\n" +
	"\x10CreateRestaurant\x12\x1d.food.CreateRestaurantRequest\x1a\x1e.food.CreateRestaurantResponse\x12C\n" +
	"\x11GetRestaurantByID\x12\x14.food.GetByIDRequest\x1a\x18.food.RestaurantResponse\x12>\n" +
	"\x11GetAllRestaurants\x12\v.food.Empty\x1a\x1c.food.RestaurantListResponse\x12>\n" +
	"\x10UpdateRestaurant\x12\x1d.food.UpdateRestaurantRequest\x1a\v.food.Empty\x125\n" +
	"\x10DeleteRestaurant\x12\x14.food.GetByIDRequest\x1a\v.food.Empty2R\n" +
	"\x11FoodFilterService\x12=\n" +
	"\n" +
	"FilterFood\x12\x17.food.FoodFilterRequest\x1a\x16.food.FoodListResponseB\x1cZ\x1afood-service/genproto/foodb\x06proto3"

var (
	file_food_food_proto_rawDescOnce sync.Once
	file_food_food_proto_rawDescData []byte
)

func file_food_food_proto_rawDescGZIP() []byte {
	file_food_food_proto_rawDescOnce.Do(func() {
		file_food_food_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_food_food_proto_rawDesc), len(file_food_food_proto_rawDesc)))
	})
	return file_food_food_proto_rawDescData
}

var file_food_food_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_food_food_proto_goTypes = []any{
	(*Empty)(nil),                    // 0: food.Empty
	(*GetByIDRequest)(nil),           // 1: food.GetByIDRequest
	(*Recipe)(nil),                   // 2: food.Recipe
	(*CreateRecipeRequest)(nil),      // 3: food.CreateRecipeRequest
	(*UpdateRecipeRequest)(nil),      // 4: food.UpdateRecipeRequest
	(*RecipeResponse)(nil),           // 5: food.RecipeResponse
	(*RecipeListResponse)(nil),       // 6: food.RecipeListResponse
	(*Salad)(nil),                    // 7: food.Salad
	(*CreateSaladRequest)(nil),       // 8: food.CreateSaladRequest
	(*UpdateSaladRequest)(nil),       // 9: food.UpdateSaladRequest
	(*SaladResponse)(nil),            // 10: food.SaladResponse
	(*SaladListResponse)(nil),        // 11: food.SaladListResponse
	(*Restaurant)(nil),               // 12: food.Restaurant
	(*CreateRestaurantRequest)(nil),  // 13: food.CreateRestaurantRequest
	(*CreateRestaurantResponse)(nil), // 14: food.CreateRestaurantResponse
	(*UpdateRestaurantRequest)(nil),  // 15: food.UpdateRestaurantRequest
	(*RestaurantResponse)(nil),       // 16: food.RestaurantResponse
	(*RestaurantListResponse)(nil),   // 17: food.RestaurantListResponse
	(*FoodFilterRequest)(nil),        // 18: food.FoodFilterRequest
	(*FoodItem)(nil),                 // 19: food.FoodItem
	(*FoodListResponse)(nil),         // 20: food.FoodListResponse
}
var file_food_food_proto_depIdxs = []int32{
	2,  // 0: food.CreateRecipeRequest.recipe:type_name -> food.Recipe
	2,  // 1: food.UpdateRecipeRequest.recipe:type_name -> food.Recipe
	2,  // 2: food.RecipeResponse.recipe:type_name -> food.Recipe
	2,  // 3: food.RecipeListResponse.recipes:type_name -> food.Recipe
	7,  // 4: food.CreateSaladRequest.salad:type_name -> food.Salad
	7,  // 5: food.UpdateSaladRequest.salad:type_name -> food.Salad
	7,  // 6: food.SaladResponse.salad:type_name -> food.Salad
	7,  // 7: food.SaladListResponse.salads:type_name -> food.Salad
	12, // 8: food.UpdateRestaurantRequest.restaurant:type_name -> food.Restaurant
	12, // 9: food.RestaurantResponse.restaurant:type_name -> food.Restaurant
	12, // 10: food.RestaurantListResponse.restaurants:type_name -> food.Restaurant
	19, // 11: food.FoodListResponse.items:type_name -> food.FoodItem
	3,  // 12: food.RecipeService.CreateRecipe:input_type -> food.CreateRecipeRequest
	1,  // 13: food.RecipeService.GetRecipeByID:input_type -> food.GetByIDRequest
	0,  // 14: food.RecipeService.GetAllRecipes:input_type -> food.Empty
	4,  // 15: food.RecipeService.UpdateRecipe:input_type -> food.UpdateRecipeRequest
	1,  // 16: food.RecipeService.DeleteRecipe:input_type -> food.GetByIDRequest
	8,  // 17: food.SaladService.CreateSalad:input_type -> food.CreateSaladRequest
	1,  // 18: food.SaladService.GetSaladByID:input_type -> food.GetByIDRequest
	0,  // 19: food.SaladService.GetAllSalads:input_type -> food.Empty
	9,  // 20: food.SaladService.UpdateSalad:input_type -> food.UpdateSaladRequest
	1,  // 21: food.SaladService.DeleteSalad:input_type -> food.GetByIDRequest
	13, // 22: food.RestaurantService.CreateRestaurant:input_type -> food.CreateRestaurantRequest
	1,  // 23: food.RestaurantService.GetRestaurantByID:input_type -> food.GetByIDRequest
	0,  // 24: food.RestaurantService.GetAllRestaurants:input_type -> food.Empty
	15, // 25: food.RestaurantService.UpdateRestaurant:input_type -> food.UpdateRestaurantRequest
	1,  // 26: food.RestaurantService.DeleteRestaurant:input_type -> food.GetByIDRequest
	18, // 27: food.FoodFilterService.FilterFood:input_type -> food.FoodFilterRequest
	0,  // 28: food.RecipeService.CreateRecipe:output_type -> food.Empty
	5,  // 29: food.RecipeService.GetRecipeByID:output_type -> food.RecipeResponse
	6,  // 30: food.RecipeService.GetAllRecipes:output_type -> food.RecipeListResponse
	0,  // 31: food.RecipeService.UpdateRecipe:output_type -> food.Empty
	0,  // 32: food.RecipeService.DeleteRecipe:output_type -> food.Empty
	0,  // 33: food.SaladService.CreateSalad:output_type -> food.Empty
	10, // 34: food.SaladService.GetSaladByID:output_type -> food.SaladResponse
	11, // 35: food.SaladService.GetAllSalads:output_type -> food.SaladListResponse
	0,  // 36: food.SaladService.UpdateSalad:output_type -> food.Empty
	0,  // 37: food.SaladService.DeleteSalad:output_type -> food.Empty
	14, // 38: food.RestaurantService.CreateRestaurant:output_type -> food.CreateRestaurantResponse
	16, // 39: food.RestaurantService.GetRestaurantByID:output_type -> food.RestaurantResponse
	17, // 40: food.RestaurantService.GetAllRestaurants:output_type -> food.RestaurantListResponse
	0,  // 41: food.RestaurantService.UpdateRestaurant:output_type -> food.Empty
	0,  // 42: food.RestaurantService.DeleteRestaurant:output_type -> food.Empty
	20, // 43: food.FoodFilterService.FilterFood:output_type -> food.FoodListResponse
	28, // [28:44] is the sub-list for method output_type
	12, // [12:28] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_food_food_proto_init() }
func file_food_food_proto_init() {
	if File_food_food_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_food_food_proto_rawDesc), len(file_food_food_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_food_food_proto_goTypes,
		DependencyIndexes: file_food_food_proto_depIdxs,
		MessageInfos:      file_food_food_proto_msgTypes,
	}.Build()
	File_food_food_proto = out.File
	file_food_food_proto_goTypes = nil
	file_food_food_proto_depIdxs = nil
}
