// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: asosiy/asosiy.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FoodFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`                       // uzbekistan | russia | korea
	MealTime      string                 `protobuf:"bytes,2,opt,name=meal_time,json=mealTime,proto3" json:"meal_time,omitempty"`     // breakfast | lunch | dinner
	HasSalad      bool                   `protobuf:"varint,3,opt,name=has_salad,json=hasSalad,proto3" json:"has_salad,omitempty"`    // true | false
	KcalLimit     int32                  `protobuf:"varint,4,opt,name=kcal_limit,json=kcalLimit,proto3" json:"kcal_limit,omitempty"` // 600 | 700 | 780
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodFilterRequest) Reset() {
	*x = FoodFilterRequest{}
	mi := &file_asosiy_asosiy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodFilterRequest) ProtoMessage() {}

func (x *FoodFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asosiy_asosiy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodFilterRequest.ProtoReflect.Descriptor instead.
func (*FoodFilterRequest) Descriptor() ([]byte, []int) {
	return file_asosiy_asosiy_proto_rawDescGZIP(), []int{0}
}

func (x *FoodFilterRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *FoodFilterRequest) GetMealTime() string {
	if x != nil {
		return x.MealTime
	}
	return ""
}

func (x *FoodFilterRequest) GetHasSalad() bool {
	if x != nil {
		return x.HasSalad
	}
	return false
}

func (x *FoodFilterRequest) GetKcalLimit() int32 {
	if x != nil {
		return x.KcalLimit
	}
	return 0
}

type FoodItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // recipe | salad
	RestaurantId  int64                  `protobuf:"varint,3,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,7,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	Country       string                 `protobuf:"bytes,8,opt,name=country,proto3" json:"country,omitempty"`
	MealTime      string                 `protobuf:"bytes,9,opt,name=meal_time,json=mealTime,proto3" json:"meal_time,omitempty"`
	Kcal          int32                  `protobuf:"varint,10,opt,name=kcal,proto3" json:"kcal,omitempty"`
	Protein       float64                `protobuf:"fixed64,11,opt,name=protein,proto3" json:"protein,omitempty"`
	Fat           float64                `protobuf:"fixed64,12,opt,name=fat,proto3" json:"fat,omitempty"`
	Carbs         float64                `protobuf:"fixed64,13,opt,name=carbs,proto3" json:"carbs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodItem) Reset() {
	*x = FoodItem{}
	mi := &file_asosiy_asosiy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodItem) ProtoMessage() {}

func (x *FoodItem) ProtoReflect() protoreflect.Message {
	mi := &file_asosiy_asosiy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodItem.ProtoReflect.Descriptor instead.
func (*FoodItem) Descriptor() ([]byte, []int) {
	return file_asosiy_asosiy_proto_rawDescGZIP(), []int{1}
}

func (x *FoodItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FoodItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FoodItem) GetRestaurantId() int64 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *FoodItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FoodItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FoodItem) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *FoodItem) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *FoodItem) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *FoodItem) GetMealTime() string {
	if x != nil {
		return x.MealTime
	}
	return ""
}

func (x *FoodItem) GetKcal() int32 {
	if x != nil {
		return x.Kcal
	}
	return 0
}

func (x *FoodItem) GetProtein() float64 {
	if x != nil {
		return x.Protein
	}
	return 0
}

func (x *FoodItem) GetFat() float64 {
	if x != nil {
		return x.Fat
	}
	return 0
}

func (x *FoodItem) GetCarbs() float64 {
	if x != nil {
		return x.Carbs
	}
	return 0
}

type FoodListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FoodItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodListResponse) Reset() {
	*x = FoodListResponse{}
	mi := &file_asosiy_asosiy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodListResponse) ProtoMessage() {}

func (x *FoodListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asosiy_asosiy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodListResponse.ProtoReflect.Descriptor instead.
func (*FoodListResponse) Descriptor() ([]byte, []int) {
	return file_asosiy_asosiy_proto_rawDescGZIP(), []int{2}
}

func (x *FoodListResponse) GetItems() []*FoodItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type FoodDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`        // recipe | salad
	Portion       int32                  `protobuf:"varint,3,opt,name=portion,proto3" json:"portion,omitempty"` // 🔥 SHU YERDA
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodDetailRequest) Reset() {
	*x = FoodDetailRequest{}
	mi := &file_asosiy_asosiy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodDetailRequest) ProtoMessage() {}

func (x *FoodDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asosiy_asosiy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodDetailRequest.ProtoReflect.Descriptor instead.
func (*FoodDetailRequest) Descriptor() ([]byte, []int) {
	return file_asosiy_asosiy_proto_rawDescGZIP(), []int{3}
}

func (x *FoodDetailRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FoodDetailRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FoodDetailRequest) GetPortion() int32 {
	if x != nil {
		return x.Portion
	}
	return 0
}

type FoodDetailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*FoodDetailResponse_Recipe
	//	*FoodDetailResponse_Salad
	Data          isFoodDetailResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodDetailResponse) Reset() {
	*x = FoodDetailResponse{}
	mi := &file_asosiy_asosiy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodDetailResponse) ProtoMessage() {}

func (x *FoodDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asosiy_asosiy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodDetailResponse.ProtoReflect.Descriptor instead.
func (*FoodDetailResponse) Descriptor() ([]byte, []int) {
	return file_asosiy_asosiy_proto_rawDescGZIP(), []int{4}
}

func (x *FoodDetailResponse) GetData() isFoodDetailResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FoodDetailResponse) GetRecipe() *Recipe {
	if x != nil {
		if x, ok := x.Data.(*FoodDetailResponse_Recipe); ok {
			return x.Recipe
		}
	}
	return nil
}

func (x *FoodDetailResponse) GetSalad() *Salad {
	if x != nil {
		if x, ok := x.Data.(*FoodDetailResponse_Salad); ok {
			return x.Salad
		}
	}
	return nil
}

type isFoodDetailResponse_Data interface {
	isFoodDetailResponse_Data()
}

type FoodDetailResponse_Recipe struct {
	Recipe *Recipe `protobuf:"bytes,1,opt,name=recipe,proto3,oneof"`
}

type FoodDetailResponse_Salad struct {
	Salad *Salad `protobuf:"bytes,2,opt,name=salad,proto3,oneof"`
}

func (*FoodDetailResponse_Recipe) isFoodDetailResponse_Data() {}

func (*FoodDetailResponse_Salad) isFoodDetailResponse_Data() {}

type Salad struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RestaurantId  int64                  `protobuf:"varint,2,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,6,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	Country       string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	MealTime      string                 `protobuf:"bytes,8,opt,name=meal_time,json=mealTime,proto3" json:"meal_time,omitempty"`
	Kcal          int32                  `protobuf:"varint,9,opt,name=kcal,proto3" json:"kcal,omitempty"`
	Protein       float64                `protobuf:"fixed64,10,opt,name=protein,proto3" json:"protein,omitempty"`
	Fat           float64                `protobuf:"fixed64,11,opt,name=fat,proto3" json:"fat,omitempty"`
	Carbs         float64                `protobuf:"fixed64,12,opt,name=carbs,proto3" json:"carbs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Salad) Reset() {
	*x = Salad{}
	mi := &file_asosiy_asosiy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Salad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Salad) ProtoMessage() {}

func (x *Salad) ProtoReflect() protoreflect.Message {
	mi := &file_asosiy_asosiy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Salad.ProtoReflect.Descriptor instead.
func (*Salad) Descriptor() ([]byte, []int) {
	return file_asosiy_asosiy_proto_rawDescGZIP(), []int{5}
}

func (x *Salad) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Salad) GetRestaurantId() int64 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *Salad) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Salad) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Salad) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Salad) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *Salad) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Salad) GetMealTime() string {
	if x != nil {
		return x.MealTime
	}
	return ""
}

func (x *Salad) GetKcal() int32 {
	if x != nil {
		return x.Kcal
	}
	return 0
}

func (x *Salad) GetProtein() float64 {
	if x != nil {
		return x.Protein
	}
	return 0
}

func (x *Salad) GetFat() float64 {
	if x != nil {
		return x.Fat
	}
	return 0
}

func (x *Salad) GetCarbs() float64 {
	if x != nil {
		return x.Carbs
	}
	return 0
}

type Recipe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RestaurantId  int64                  `protobuf:"varint,2,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,6,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	Country       string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	MealTime      string                 `protobuf:"bytes,8,opt,name=meal_time,json=mealTime,proto3" json:"meal_time,omitempty"`
	Kcal          int32                  `protobuf:"varint,9,opt,name=kcal,proto3" json:"kcal,omitempty"`
	Protein       float64                `protobuf:"fixed64,10,opt,name=protein,proto3" json:"protein,omitempty"`
	Fat           float64                `protobuf:"fixed64,11,opt,name=fat,proto3" json:"fat,omitempty"`
	Carbs         float64                `protobuf:"fixed64,12,opt,name=carbs,proto3" json:"carbs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recipe) Reset() {
	*x = Recipe{}
	mi := &file_asosiy_asosiy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recipe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipe) ProtoMessage() {}

func (x *Recipe) ProtoReflect() protoreflect.Message {
	mi := &file_asosiy_asosiy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipe.ProtoReflect.Descriptor instead.
func (*Recipe) Descriptor() ([]byte, []int) {
	return file_asosiy_asosiy_proto_rawDescGZIP(), []int{6}
}

func (x *Recipe) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Recipe) GetRestaurantId() int64 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *Recipe) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Recipe) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Recipe) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Recipe) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *Recipe) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Recipe) GetMealTime() string {
	if x != nil {
		return x.MealTime
	}
	return ""
}

func (x *Recipe) GetKcal() int32 {
	if x != nil {
		return x.Kcal
	}
	return 0
}

func (x *Recipe) GetProtein() float64 {
	if x != nil {
		return x.Protein
	}
	return 0
}

func (x *Recipe) GetFat() float64 {
	if x != nil {
		return x.Fat
	}
	return 0
}

func (x *Recipe) GetCarbs() float64 {
	if x != nil {
		return x.Carbs
	}
	return 0
}

var File_asosiy_asosiy_proto protoreflect.FileDescriptor

const file_asosiy_asosiy_proto_rawDesc = "" +
	"\n" +
	"\x13asosiy/asosiy.proto\x12\x06asosiy\"\x86\x01\n" +
	"\x11FoodFilterRequest\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x1b\n" +
	"\tmeal_time\x18\x02 \x01(\tR\bmealTime\x12\x1b\n" +
	"\thas_salad\x18\x03 \x01(\bR\bhasSalad\x12\x1d\n" +
	"\n" +
	"kcal_limit\x18\x04 \x01(\x05R\tkcalLimit\"\xd0\x02\n" +
	"\bFoodItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12#\n" +
	"\rrestaurant_id\x18\x03 \x01(\x03R\frestaurantId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tvideo_url\x18\a \x01(\tR\bvideoUrl\x12\x18\n" +
	"\acountry\x18\b \x01(\tR\acountry\x12\x1b\n" +
	"\tmeal_time\x18\t \x01(\tR\bmealTime\x12\x12\n" +
	"\x04kcal\x18\n" +
	" \x01(\x05R\x04kcal\x12\x18\n" +
	"\aprotein\x18\v \x01(\x01R\aprotein\x12\x10\n" +
	"\x03fat\x18\f \x01(\x01R\x03fat\x12\x14\n" +
	"\x05carbs\x18\r \x01(\x01R\x05carbs\":\n" +
	"\x10FoodListResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.asosiy.FoodItemR\x05items\"Q\n" +
	"\x11FoodDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\aportion\x18\x03 \x01(\x05R\aportion\"m\n" +
	"\x12FoodDetailResponse\x12(\n" +
	"\x06recipe\x18\x01 \x01(\v2\x0e.asosiy.RecipeH\x00R\x06recipe\x12%\n" +
	"\x05salad\x18\x02 \x01(\v2\r.asosiy.SaladH\x00R\x05saladB\x06\n" +
	"\x04data\"\xb9\x02\n" +
	"\x05Salad\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rrestaurant_id\x18\x02 \x01(\x03R\frestaurantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tvideo_url\x18\x06 \x01(\tR\bvideoUrl\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12\x1b\n" +
	"\tmeal_time\x18\b \x01(\tR\bmealTime\x12\x12\n" +
	"\x04kcal\x18\t \x01(\x05R\x04kcal\x12\x18\n" +
	"\aprotein\x18\n" +
	" \x01(\x01R\aprotein\x12\x10\n" +
	"\x03fat\x18\v \x01(\x01R\x03fat\x12\x14\n" +
	"\x05carbs\x18\f \x01(\x01R\x05carbs\"\xba\x02\n" +
	"\x06Recipe\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rrestaurant_id\x18\x02 \x01(\x03R\frestaurantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tvideo_url\x18\x06 \x01(\tR\bvideoUrl\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12\x1b\n" +
	"\tmeal_time\x18\b \x01(\tR\bmealTime\x12\x12\n" +
	"\x04kcal\x18\t \x01(\x05R\x04kcal\x12\x18\n" +
	"\aprotein\x18\n" +
	" \x01(\x01R\aprotein\x12\x10\n" +
	"\x03fat\x18\v \x01(\x01R\x03fat\x12\x14\n" +
	"\x05carbs\x18\f \x01(\x01R\x05carbs2\x98\x01\n" +
	"\vFoodService\x12A\n" +
	"\n" +
	"FilterFood\x12\x19.asosiy.FoodFilterRequest\x1a\x18.asosiy.FoodListResponse\x12F\n" +
	"\rGetFoodDetail\x12\x19.asosiy.FoodDetailRequest\x1a\x1a.asosiy.FoodDetailResponseB\x16Z\x14asosiy-service/protob\x06proto3"

var (
	file_asosiy_asosiy_proto_rawDescOnce sync.Once
	file_asosiy_asosiy_proto_rawDescData []byte
)

func file_asosiy_asosiy_proto_rawDescGZIP() []byte {
	file_asosiy_asosiy_proto_rawDescOnce.Do(func() {
		file_asosiy_asosiy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asosiy_asosiy_proto_rawDesc), len(file_asosiy_asosiy_proto_rawDesc)))
	})
	return file_asosiy_asosiy_proto_rawDescData
}

var file_asosiy_asosiy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_asosiy_asosiy_proto_goTypes = []any{
	(*FoodFilterRequest)(nil),  // 0: asosiy.FoodFilterRequest
	(*FoodItem)(nil),           // 1: asosiy.FoodItem
	(*FoodListResponse)(nil),   // 2: asosiy.FoodListResponse
	(*FoodDetailRequest)(nil),  // 3: asosiy.FoodDetailRequest
	(*FoodDetailResponse)(nil), // 4: asosiy.FoodDetailResponse
	(*Salad)(nil),              // 5: asosiy.Salad
	(*Recipe)(nil),             // 6: asosiy.Recipe
}
var file_asosiy_asosiy_proto_depIdxs = []int32{
	1, // 0: asosiy.FoodListResponse.items:type_name -> asosiy.FoodItem
	6, // 1: asosiy.FoodDetailResponse.recipe:type_name -> asosiy.Recipe
	5, // 2: asosiy.FoodDetailResponse.salad:type_name -> asosiy.Salad
	0, // 3: asosiy.FoodService.FilterFood:input_type -> asosiy.FoodFilterRequest
	3, // 4: asosiy.FoodService.GetFoodDetail:input_type -> asosiy.FoodDetailRequest
	2, // 5: asosiy.FoodService.FilterFood:output_type -> asosiy.FoodListResponse
	4, // 6: asosiy.FoodService.GetFoodDetail:output_type -> asosiy.FoodDetailResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_asosiy_asosiy_proto_init() }
func file_asosiy_asosiy_proto_init() {
	if File_asosiy_asosiy_proto != nil {
		return
	}
	file_asosiy_asosiy_proto_msgTypes[4].OneofWrappers = []any{
		(*FoodDetailResponse_Recipe)(nil),
		(*FoodDetailResponse_Salad)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asosiy_asosiy_proto_rawDesc), len(file_asosiy_asosiy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_asosiy_asosiy_proto_goTypes,
		DependencyIndexes: file_asosiy_asosiy_proto_depIdxs,
		MessageInfos:      file_asosiy_asosiy_proto_msgTypes,
	}.Build()
	File_asosiy_asosiy_proto = out.File
	file_asosiy_asosiy_proto_goTypes = nil
	file_asosiy_asosiy_proto_depIdxs = nil
}
