// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: asosiy/asosiy.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FoodService_FilterFood_FullMethodName    = "/asosiy.FoodService/FilterFood"
	FoodService_GetFoodDetail_FullMethodName = "/asosiy.FoodService/GetFoodDetail"
)

// FoodServiceClient is the client API for FoodService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FoodServiceClient interface {
	FilterFood(ctx context.Context, in *FoodFilterRequest, opts ...grpc.CallOption) (*FoodListResponse, error)
	GetFoodDetail(ctx context.Context, in *FoodDetailRequest, opts ...grpc.CallOption) (*FoodDetailResponse, error)
}

type foodServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFoodServiceClient(cc grpc.ClientConnInterface) FoodServiceClient {
	return &foodServiceClient{cc}
}

func (c *foodServiceClient) FilterFood(ctx context.Context, in *FoodFilterRequest, opts ...grpc.CallOption) (*FoodListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FoodListResponse)
	err := c.cc.Invoke(ctx, FoodService_FilterFood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *foodServiceClient) GetFoodDetail(ctx context.Context, in *FoodDetailRequest, opts ...grpc.CallOption) (*FoodDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FoodDetailResponse)
	err := c.cc.Invoke(ctx, FoodService_GetFoodDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FoodServiceServer is the server API for FoodService service.
// All implementations must embed UnimplementedFoodServiceServer
// for forward compatibility.
type FoodServiceServer interface {
	FilterFood(context.Context, *FoodFilterRequest) (*FoodListResponse, error)
	GetFoodDetail(context.Context, *FoodDetailRequest) (*FoodDetailResponse, error)
	mustEmbedUnimplementedFoodServiceServer()
}

// UnimplementedFoodServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFoodServiceServer struct{}

func (UnimplementedFoodServiceServer) FilterFood(context.Context, *FoodFilterRequest) (*FoodListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FilterFood not implemented")
}
func (UnimplementedFoodServiceServer) GetFoodDetail(context.Context, *FoodDetailRequest) (*FoodDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFoodDetail not implemented")
}
func (UnimplementedFoodServiceServer) mustEmbedUnimplementedFoodServiceServer() {}
func (UnimplementedFoodServiceServer) testEmbeddedByValue()                     {}

// UnsafeFoodServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FoodServiceServer will
// result in compilation errors.
type UnsafeFoodServiceServer interface {
	mustEmbedUnimplementedFoodServiceServer()
}

func RegisterFoodServiceServer(s grpc.ServiceRegistrar, srv FoodServiceServer) {
	// If the following call panics, it indicates UnimplementedFoodServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FoodService_ServiceDesc, srv)
}

func _FoodService_FilterFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FoodFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServiceServer).FilterFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FoodService_FilterFood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServiceServer).FilterFood(ctx, req.(*FoodFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FoodService_GetFoodDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FoodDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServiceServer).GetFoodDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FoodService_GetFoodDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServiceServer).GetFoodDetail(ctx, req.(*FoodDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FoodService_ServiceDesc is the grpc.ServiceDesc for FoodService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FoodService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "asosiy.FoodService",
	HandlerType: (*FoodServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FilterFood",
			Handler:    _FoodService_FilterFood_Handler,
		},
		{
			MethodName: "GetFoodDetail",
			Handler:    _FoodService_GetFoodDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "asosiy/asosiy.proto",
}
