// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: products/category.proto

package categorypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_products_category_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_products_category_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_products_category_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Ingredient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      float64                `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ingredient) Reset() {
	*x = Ingredient{}
	mi := &file_products_category_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ingredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ingredient) ProtoMessage() {}

func (x *Ingredient) ProtoReflect() protoreflect.Message {
	mi := &file_products_category_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ingredient.ProtoReflect.Descriptor instead.
func (*Ingredient) Descriptor() ([]byte, []int) {
	return file_products_category_proto_rawDescGZIP(), []int{1}
}

func (x *Ingredient) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Ingredient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ingredient) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CategoryWithIngredients struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Items         []*Ingredient          `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryWithIngredients) Reset() {
	*x = CategoryWithIngredients{}
	mi := &file_products_category_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryWithIngredients) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryWithIngredients) ProtoMessage() {}

func (x *CategoryWithIngredients) ProtoReflect() protoreflect.Message {
	mi := &file_products_category_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryWithIngredients.ProtoReflect.Descriptor instead.
func (*CategoryWithIngredients) Descriptor() ([]byte, []int) {
	return file_products_category_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryWithIngredients) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CategoryWithIngredients) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryWithIngredients) GetItems() []*Ingredient {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_products_category_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_category_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_products_category_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDRequest) Reset() {
	*x = GetByIDRequest{}
	mi := &file_products_category_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDRequest) ProtoMessage() {}

func (x *GetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_category_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return file_products_category_proto_rawDescGZIP(), []int{4}
}

func (x *GetByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_products_category_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_category_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_products_category_proto_rawDescGZIP(), []int{5}
}

type UpdateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryRequest) Reset() {
	*x = UpdateCategoryRequest{}
	mi := &file_products_category_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRequest) ProtoMessage() {}

func (x *UpdateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_category_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_products_category_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCategoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryRequest) Reset() {
	*x = DeleteCategoryRequest{}
	mi := &file_products_category_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryRequest) ProtoMessage() {}

func (x *DeleteCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_category_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return file_products_category_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCategoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAllWithUserProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllWithUserProductsRequest) Reset() {
	*x = GetAllWithUserProductsRequest{}
	mi := &file_products_category_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllWithUserProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllWithUserProductsRequest) ProtoMessage() {}

func (x *GetAllWithUserProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_category_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllWithUserProductsRequest.ProtoReflect.Descriptor instead.
func (*GetAllWithUserProductsRequest) Descriptor() ([]byte, []int) {
	return file_products_category_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllWithUserProductsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryResponse) Reset() {
	*x = CategoryResponse{}
	mi := &file_products_category_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryResponse) ProtoMessage() {}

func (x *CategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_category_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryResponse.ProtoReflect.Descriptor instead.
func (*CategoryResponse) Descriptor() ([]byte, []int) {
	return file_products_category_proto_rawDescGZIP(), []int{9}
}

func (x *CategoryResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type CategoryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryListResponse) Reset() {
	*x = CategoryListResponse{}
	mi := &file_products_category_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListResponse) ProtoMessage() {}

func (x *CategoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_category_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListResponse.ProtoReflect.Descriptor instead.
func (*CategoryListResponse) Descriptor() ([]byte, []int) {
	return file_products_category_proto_rawDescGZIP(), []int{10}
}

func (x *CategoryListResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CategoryWithIngredientsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Category      *CategoryWithIngredients `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryWithIngredientsResponse) Reset() {
	*x = CategoryWithIngredientsResponse{}
	mi := &file_products_category_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryWithIngredientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryWithIngredientsResponse) ProtoMessage() {}

func (x *CategoryWithIngredientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_category_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryWithIngredientsResponse.ProtoReflect.Descriptor instead.
func (*CategoryWithIngredientsResponse) Descriptor() ([]byte, []int) {
	return file_products_category_proto_rawDescGZIP(), []int{11}
}

func (x *CategoryWithIngredientsResponse) GetCategory() *CategoryWithIngredients {
	if x != nil {
		return x.Category
	}
	return nil
}

type CategoryWithIngredientsListResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Categories    []*CategoryWithIngredients `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryWithIngredientsListResponse) Reset() {
	*x = CategoryWithIngredientsListResponse{}
	mi := &file_products_category_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryWithIngredientsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryWithIngredientsListResponse) ProtoMessage() {}

func (x *CategoryWithIngredientsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_category_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryWithIngredientsListResponse.ProtoReflect.Descriptor instead.
func (*CategoryWithIngredientsListResponse) Descriptor() ([]byte, []int) {
	return file_products_category_proto_rawDescGZIP(), []int{12}
}

func (x *CategoryWithIngredientsListResponse) GetCategories() []*CategoryWithIngredients {
	if x != nil {
		return x.Categories
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_products_category_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_products_category_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_products_category_proto_rawDescGZIP(), []int{13}
}

var File_products_category_proto protoreflect.FileDescriptor

const file_products_category_proto_rawDesc = "" +
	"\n" +
	"\x17products/category.proto\x12\bcategory\"M\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"L\n" +
	"\n" +
	"Ingredient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x01R\bquantity\"z\n" +
	"\x17CategoryWithIngredients\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x05items\x18\x03 \x03(\v2\x14.category.IngredientR\x05items\"+\n" +
	"\x15CreateCategoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\" \n" +
	"\x0eGetByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x0f\n" +
	"\rGetAllRequest\";\n" +
	"\x15UpdateCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"'\n" +
	"\x15DeleteCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"8\n" +
	"\x1dGetAllWithUserProductsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"B\n" +
	"\x10CategoryResponse\x12.\n" +
	"\bcategory\x18\x01 \x01(\v2\x12.category.CategoryR\bcategory\"J\n" +
	"\x14CategoryListResponse\x122\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x12.category.CategoryR\n" +
	"categories\"`\n" +
	"\x1fCategoryWithIngredientsResponse\x12=\n" +
	"\bcategory\x18\x01 \x01(\v2!.category.CategoryWithIngredientsR\bcategory\"h\n" +
	"#CategoryWithIngredientsListResponse\x12A\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2!.category.CategoryWithIngredientsR\n" +
	"categories\"\a\n" +
	"\x05Empty2\xe0\x03\n" +
	"\x0fCategoryService\x12E\n" +
	"\x06Create\x12\x1f.category.CreateCategoryRequest\x1a\x1a.category.CategoryResponse\x12N\n" +
	"\aGetByID\x12\x18.category.GetByIDRequest\x1a).category.CategoryWithIngredientsResponse\x12A\n" +
	"\x06GetAll\x12\x17.category.GetAllRequest\x1a\x1e.category.CategoryListResponse\x12E\n" +
	"\x06Update\x12\x1f.category.UpdateCategoryRequest\x1a\x1a.category.CategoryResponse\x12:\n" +
	"\x06Delete\x12\x1f.category.DeleteCategoryRequest\x1a\x0f.category.Empty\x12p\n" +
	"\x16GetAllWithUserProducts\x12'.category.GetAllWithUserProductsRequest\x1a-.category.CategoryWithIngredientsListResponseB?Z=github.com/khbdev/what-food-proto/proto/categorypb;categorypbb\x06proto3"

var (
	file_products_category_proto_rawDescOnce sync.Once
	file_products_category_proto_rawDescData []byte
)

func file_products_category_proto_rawDescGZIP() []byte {
	file_products_category_proto_rawDescOnce.Do(func() {
		file_products_category_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_products_category_proto_rawDesc), len(file_products_category_proto_rawDesc)))
	})
	return file_products_category_proto_rawDescData
}

var file_products_category_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_products_category_proto_goTypes = []any{
	(*Category)(nil),                            // 0: category.Category
	(*Ingredient)(nil),                          // 1: category.Ingredient
	(*CategoryWithIngredients)(nil),             // 2: category.CategoryWithIngredients
	(*CreateCategoryRequest)(nil),               // 3: category.CreateCategoryRequest
	(*GetByIDRequest)(nil),                      // 4: category.GetByIDRequest
	(*GetAllRequest)(nil),                       // 5: category.GetAllRequest
	(*UpdateCategoryRequest)(nil),               // 6: category.UpdateCategoryRequest
	(*DeleteCategoryRequest)(nil),               // 7: category.DeleteCategoryRequest
	(*GetAllWithUserProductsRequest)(nil),       // 8: category.GetAllWithUserProductsRequest
	(*CategoryResponse)(nil),                    // 9: category.CategoryResponse
	(*CategoryListResponse)(nil),                // 10: category.CategoryListResponse
	(*CategoryWithIngredientsResponse)(nil),     // 11: category.CategoryWithIngredientsResponse
	(*CategoryWithIngredientsListResponse)(nil), // 12: category.CategoryWithIngredientsListResponse
	(*Empty)(nil),                               // 13: category.Empty
}
var file_products_category_proto_depIdxs = []int32{
	1,  // 0: category.CategoryWithIngredients.items:type_name -> category.Ingredient
	0,  // 1: category.CategoryResponse.category:type_name -> category.Category
	0,  // 2: category.CategoryListResponse.categories:type_name -> category.Category
	2,  // 3: category.CategoryWithIngredientsResponse.category:type_name -> category.CategoryWithIngredients
	2,  // 4: category.CategoryWithIngredientsListResponse.categories:type_name -> category.CategoryWithIngredients
	3,  // 5: category.CategoryService.Create:input_type -> category.CreateCategoryRequest
	4,  // 6: category.CategoryService.GetByID:input_type -> category.GetByIDRequest
	5,  // 7: category.CategoryService.GetAll:input_type -> category.GetAllRequest
	6,  // 8: category.CategoryService.Update:input_type -> category.UpdateCategoryRequest
	7,  // 9: category.CategoryService.Delete:input_type -> category.DeleteCategoryRequest
	8,  // 10: category.CategoryService.GetAllWithUserProducts:input_type -> category.GetAllWithUserProductsRequest
	9,  // 11: category.CategoryService.Create:output_type -> category.CategoryResponse
	11, // 12: category.CategoryService.GetByID:output_type -> category.CategoryWithIngredientsResponse
	10, // 13: category.CategoryService.GetAll:output_type -> category.CategoryListResponse
	9,  // 14: category.CategoryService.Update:output_type -> category.CategoryResponse
	13, // 15: category.CategoryService.Delete:output_type -> category.Empty
	12, // 16: category.CategoryService.GetAllWithUserProducts:output_type -> category.CategoryWithIngredientsListResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_products_category_proto_init() }
func file_products_category_proto_init() {
	if File_products_category_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_products_category_proto_rawDesc), len(file_products_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_products_category_proto_goTypes,
		DependencyIndexes: file_products_category_proto_depIdxs,
		MessageInfos:      file_products_category_proto_msgTypes,
	}.Build()
	File_products_category_proto = out.File
	file_products_category_proto_goTypes = nil
	file_products_category_proto_depIdxs = nil
}
